import { sidebar } from "vuepress-theme-hope";

// 由 scripts/gen-sidebar.mjs 自动生成，请勿手改。
// 新增分类：直接建子文件夹；权限书稿可在分类下再建卷目录（二级侧栏）。
// 新增文章：放入对应文件夹并写 shortTitle / order / sidebarGroup
// icon / 显示名 / 分类顺序可在 scripts/sidebar/<模块>.mjs 里覆盖
// 然后运行：pnpm sidebar:gen
export default sidebar({
  "/Ai/": [
    "",
    {
      text: "学习路线",
      icon: "route",
      prefix: "roadmap/",
      collapsible: true,
      children: [
        "aicon-2026-roadmap",
      ],
    },
    {
      text: "阶段 0 · 大模型地基",
      icon: "lightbulb",
      prefix: "0-llm-basics/",
      collapsible: true,
      children: [
        "llm-basics-01-next-token",
        "llm-basics-02-context-window",
        "llm-basics-03-training-paradigms",
        "llm-basics-04-local-model",
        "llm-basics-05-model-card",
      ],
    },
    {
      text: "阶段 1 · 模型编程主干",
      icon: "robot",
      prefix: "1-model-api/",
      collapsible: true,
      children: [
        "model-api-01-prompt-trio",
        "model-api-02-structured-output",
        "model-api-03-function-calling",
        "model-api-04-multi-turn-memory",
        "model-api-05-context-compression",
      ],
    },
    {
      text: "阶段 2 · RAG 与数据",
      icon: "book",
      prefix: "2-rag-systems/",
      collapsible: true,
      children: [
        "rag-systems-01-embedding",
        "rag-systems-02-chunking",
        "rag-systems-03-hybrid-retrieval",
        "rag-systems-04-evaluation",
        "rag-systems-05-agentic-data",
      ],
    },
    {
      text: "阶段 3 · Agent 工程",
      icon: "robot",
      prefix: "3-agent-core/",
      collapsible: true,
      children: [
        "agent-core-01-react-loop",
        "agent-core-02-tool-design",
        "agent-core-03-mcp",
        "agent-core-04-planning",
        "agent-core-05-multi-agent",
        "agent-core-06-sandbox",
      ],
    },
    {
      text: "阶段 4 · Harness 工程",
      icon: "server",
      prefix: "4-harness/",
      collapsible: true,
      children: [
        "harness-01-context-engineering",
        "harness-02-evals",
        "harness-03-observability",
        "harness-04-agent-security",
        "harness-05-controllable-agent",
      ],
    },
    {
      text: "阶段 5 · 推理与 AI Infra",
      icon: "server",
      prefix: "5-inference-infra/",
      collapsible: true,
      children: [
        "inference-infra-01-prefill-decode",
        "inference-infra-02-kv-cache-ledger",
        "inference-infra-03-paged-attention",
        "inference-infra-04-prefix-cache",
        "inference-infra-05-long-context-pd",
        "inference-infra-06-quantization",
        "inference-infra-07-spec-decoding-moe",
        "inference-infra-08-heterogeneous-scheduling",
        "inference-infra-09-rl-infra",
      ],
    },
    {
      text: "阶段 6 · 前沿扫描",
      icon: "lightbulb",
      prefix: "6-frontier/",
      collapsible: true,
      children: [
        "frontier-01-multimodal",
        "frontier-02-embodied-vla",
        "frontier-03-edge-superapp",
        "frontier-04-coding-agent",
        "frontier-05-business-org",
      ],
    },
    {
      text: "阶段 7 · 毕业参会",
      icon: "route",
      prefix: "7-capstone/",
      collapsible: true,
      children: [
        "capstone-01-three-question-notes",
        "capstone-02-review-article",
        "capstone-03-self-check",
      ],
    },
    {
      text: "自动化 / Playwright",
      icon: "robot",
      prefix: "playwright/",
      collapsible: true,
      children: [
        "playwright-cli-learn",
        "playwright-Agent-Skills",
        "playwright-Agent-Skills-Ai-News",
        "LangChain-Learn",
      ],
    },
    {
      text: "RAG / LangChain",
      icon: "book",
      prefix: "rag/",
      collapsible: true,
      children: [
        "langchain-rag",
      ],
    },
    {
      text: "本地模型",
      icon: "server",
      prefix: "local-llm/",
      collapsible: true,
      children: [
        "ollama-opencode-local-llm",
        "qwen3-5-27b-deep-dive",
      ],
    },
    {
      text: "Agent / 方法论",
      icon: "lightbulb",
      prefix: "agent/",
      collapsible: true,
      children: [
        "how-to-build-tech-info-radar",
        "harness-engineering",
        "2026年AI-Agent框架选型指南：从“大爆发”到“大灭绝”后的生存法则",
        "agent-docker-sandbox-dialogue",
      ],
    },
    {
      text: "基础知识",
      icon: "book",
      prefix: "基础知识/",
      collapsible: true,
      children: [
        "harness-engineering",
      ],
    },
    {
      text: "Spring AI",
      icon: "robot",
      prefix: "spring-ai/",
      collapsible: true,
      children: [
        "sai-01-features",
        "sai-02-quickstart",
        "sai-03-chatclient",
        "sai-04-prompt",
        "sai-05-advisor",
        "sai-06-memory",
        "sai-07-structured-tools",
        "sai-08-function-call",
        "sai-09-mcp",
        "sai-10-rag",
        "sai-11-airline-rag",
        "sai-12-knowledge-base",
        "sai-13-rag-eval",
        "sai-14-observability",
        "sai-15-agent-patterns",
        "sai-16-v11-update",
      ],
    },
    {
      text: "Spring AI Alibaba",
      icon: "robot",
      prefix: "spring-ai-alibaba/",
      collapsible: true,
      children: [
        "saa-01-know-agent",
        "saa-02-quickstart",
        "saa-03-deep-usage",
        "saa-04-hooks-interceptors",
        "saa-05-skills",
        "saa-05b-xiaolongxia",
        "saa-06-multi-agent",
        "saa-07-graph-hr",
      ],
    },
  ],
  "/BigData/": [
    "",
    {
      text: "Hadoop 系列",
      icon: "database",
      prefix: "hadoop-series/",
      collapsible: true,
      children: [
        "hadoop-series-01-what-is-hadoop",
        "hadoop-series-02-hdfs-core-concepts",
        "hadoop-series-03-hdfs-read-write",
        "hadoop-series-04-mapreduce",
        "hadoop-series-05-yarn",
        "hadoop-series-06-hive",
        "hadoop-series-07-kafka-hadoop",
        "hadoop-series-08-hbase",
        "hadoop-series-09-data-warehouse",
        "hadoop-series-10-future",
      ],
    },
    {
      text: "实战与概念",
      icon: "flask",
      prefix: "practice/",
      collapsible: true,
      children: [
        "hadoop-docker-wordcount-demo",
        "lambda-kappa-architecture-concepts",
      ],
    },
  ],
  "/DotNet/": [
    "",
    {
      text: "ASP.NET Core",
      icon: "code",
      prefix: "aspnetcore/",
      collapsible: true,
      children: [
        "1-kestrel-socket-connection-listener",
        "2-aspnetcore-request-pipeline-debug",
        "3-aspnetcore-10-source-map",
        "4-aspnetcore-10-source-build-retrospective",
      ],
    },
  ],
  "/Java/": [
    "",
    {
      text: "源码调试",
      icon: "code",
      prefix: "source-debug/",
      collapsible: true,
      children: [
        "mybatis-source-debug-setup",
      ],
    },
    {
      text: "Spring Boot",
      icon: "leaf",
      prefix: "springboot/",
      collapsible: true,
      children: [
        "boot-sse-01-principle-and-sseemitter",
        "boot-sse-02-webflux",
      ],
    },
  ],
  "/Windows/": [
    "",
    {
      text: "权限",
      icon: "shield-halved",
      prefix: "permissions/",
      collapsible: true,
      children: [
        "00-index",
        {
          text: "卷一·发明权限",
          icon: "book",
          prefix: "vol1-invent/",
          collapsible: true,
          children: [
            "01-no-permission",
            "02-account",
            "03-sid",
            "04-name-sid-lsa",
            "05-logon-lsa",
            "06-access-token",
            "07-owner",
            "08-permission-bits",
            "09-groups",
            "10-ace-dacl",
            "11-access-check",
            "12-security-descriptor",
            "13-inheritance",
            "14-effective-permissions",
            "15-sacl",
          ],
        },
        {
          text: "卷二·网上的身份",
          icon: "book",
          prefix: "vol2-identity/",
          collapsible: true,
          children: [
            "01-domain-dc",
            "02-kerberos",
            "03-ntlm",
            "04-logon-types",
            "05-spn",
          ],
        },
        {
          text: "卷三·权利与 UAC",
          icon: "book",
          prefix: "vol3-rights-uac/",
          collapsible: true,
          children: [
            "01-rights-uac",
            "02-user-rights",
            "03-uac",
            "04-gpo-rights",
            "05-adminsdholder",
          ],
        },
        {
          text: "卷四·不只是文件",
          icon: "book",
          prefix: "vol4-beyond-files/",
          collapsible: true,
          children: [
            "01-registry",
            "02-services",
            "03-ad-delegation",
          ],
        },
        {
          text: "卷五·排障与设计",
          icon: "book",
          prefix: "vol5-ops/",
          collapsible: true,
          children: [
            "01-share-design",
            "02-effective-access-practice",
            "03-troubleshooting-cases",
          ],
        },
        {
          text: "卷六·用代码改权限",
          icon: "book",
          prefix: "vol6-dotnet/",
          collapsible: true,
          children: [
            "01-identity",
            "02-acl",
            "03-impersonation",
          ],
        },
        {
          text: "附录",
          icon: "book",
          prefix: "appendix/",
          collapsible: true,
          children: [
            "01-map",
            "02-sddl",
            "03-event-ids",
            "04-lab",
            "05-references",
          ],
        },
        {
          text: "卷七·安全防护",
          icon: "folder",
          prefix: "vol7-defense/",
          collapsible: true,
          children: [
            "01-windows-hello",
            "02-credential-guard",
            "03-vbs-hvci",
            "04-app-control",
            "05-bitlocker",
          ],
        },
      ],
    },
    {
      text: "环境搭建",
      icon: "laptop-code",
      prefix: "setup/",
      collapsible: true,
      children: [
        "windows-wsl-docker-hadoop-setup",
        "fix-jekyll-build-on-windows",
      ],
    },
  ],
  "/Tools/": [
    "",
    {
      text: "编码与发布",
      icon: "file-code",
      prefix: "encoding-publish/",
      collapsible: true,
      children: [
        "Utf8_And_Unicode",
        "how-a-local-folder-gets-published-to-github",
      ],
    },
    {
      text: "Git / 代理",
      icon: "network-wired",
      prefix: "git-proxy/",
      collapsible: true,
      children: [
        "git-proxy-internal-repo-fix",
        "clash-verge-tun-mode-git-ssh-fix",
      ],
    },
    {
      text: "其他工具",
      icon: "screwdriver-wrench",
      prefix: "misc/",
      collapsible: true,
      children: [
        "yt-dlp的使用",
      ],
    },
    {
      text: "网络抓包",
      icon: "folder",
      prefix: "tcpdump/",
      collapsible: true,
      children: [
        "tcpdump-classroom-dialogue",
      ],
    },
  ],
  "/English/": [
    "",
    {
      text: "语法",
      icon: "book",
      prefix: "grammar/",
      collapsible: true,
      children: [
        "all-tenses-learn-english",
      ],
    },
    {
      text: "论文生词",
      icon: "language",
      prefix: "vocabulary/",
      collapsible: true,
      children: [
        "eventual-consistency-b1-vocabulary",
      ],
    },
  ],
  "/Notes/": [
    "",
    {
      text: "HAMi",
      icon: "microchip",
      prefix: "hami/",
      collapsible: true,
      children: [
        "Hami",
        "Hami-Learning",
        "Hami-Use",
        "Hami-UseTo-Make-Money",
      ],
    },
    {
      text: "基础概念",
      icon: "lightbulb",
      prefix: "concepts/",
      collapsible: true,
      children: [
        "one-hot",
        "math-jax",
      ],
    },
    {
      text: "项目与工作流",
      icon: "diagram-project",
      prefix: "projects/",
      collapsible: true,
      children: [
        "zero-to-hero-auto-warehouse",
        "project-learning-map",
        "three-blog-skills-for-retrospective-and-publish",
        "wechat-miniprogram-fangxiaotuan-mitm-retrospective",
        "wechat-miniprogram-fangxiaotuan-wmpfdebugger-cdp-runtime",
        "hello-202026",
      ],
    },
    {
      text: "思考",
      icon: "folder",
      prefix: "think/",
      collapsible: true,
      children: [
        "技术专家10问自查清单",
        "博客写作规范",
      ],
    },
    {
      text: "工具",
      icon: "folder",
      prefix: "tools/",
      collapsible: true,
      children: [
        "proxifier",
        "mitmproxy",
        "mitmweb",
        "wechat-mmtls",
        "wmpfdebugger",
      ],
    },
  ],
  "/Linux/": [
    "",
    {
      text: "Linux 基础",
      icon: "terminal",
      prefix: "basics/",
      collapsible: true,
      children: [
        "linux-01-nsenter-prerequisites",
        "linux-02-ip-subnet-gateway",
        "linux-03-tcpdump",
        "linux-04-nat",
        "linux-05-netns-iptables",
        "linux-06-bind-mount",
      ],
    },
    {
      text: "Nginx",
      icon: "server",
      prefix: "nginx/",
      collapsible: true,
      children: [
        "nginx-01-what-is-nginx",
        "nginx-02-install-and-control",
        "nginx-03-config-and-request",
        "nginx-04-static-and-vhost",
        "nginx-05-reverse-proxy",
        "nginx-06-load-balancing",
        "nginx-07-https-tls",
        "nginx-08-location-rewrite",
        "nginx-09-cache-gzip",
        "nginx-10-access-limit",
        "nginx-11-logging-debug",
        "nginx-12-performance-checklist",
      ],
    },
  ],
  "/云原生/": [
    "",
    {
      text: "云原生基础",
      icon: "seedling",
      prefix: "foundation/",
      collapsible: true,
      children: [
        "foundation-01-云原生",
        "foundation-02-虚拟化技术",
        "foundation-03-云计算",
      ],
    },
    {
      text: "Docker",
      icon: "cube",
      prefix: "docker/",
      collapsible: true,
      children: [
        "docker-00-roadmap",
        "docker-01-what-is-docker",
        "docker-a01-container-runtime-docker",
        "docker-02-container-vs-vm",
        "docker-a02-containerd",
        "docker-03-engine-platform",
        "docker-04-install",
        "docker-05-container-and-image",
        "docker-06-container-commands",
        "docker-07-enter-container",
        "docker-08-image-transfer",
        "docker-09-dockerfile",
        "docker-10-build-advanced",
        "docker-11-buildx-bake",
        "docker-12-harbor",
        "docker-13-harbor-usage",
        "docker-14-data-persistence",
        "docker-15-network",
        "docker-16-compose",
        "docker-17-https-nginx",
        "docker-18-compose-modern",
        "docker-19-tech-foundation",
        "docker-20-namespace",
        "docker-21-cgroups",
        "docker-22-unionfs",
        "docker-23-daemon-runtime",
        "docker-24-process-view",
        "docker-25-container-security",
        "docker-26-rootless",
        "docker-27-logging-monitoring",
        "docker-28-daemon-ops",
        "docker-29-swarm",
        "docker-30-supply-chain",
        "docker-31-engine-api",
        "docker-32-ai-surface",
        "docker-33-trufor-image-packaging",
      ],
    },
    {
      text: "Kubernetes",
      icon: "dharmachakra",
      prefix: "k8s/",
      collapsible: true,
      children: [
        "k8s-00-roadmap",
        "k8s-01-cloud-native",
        "k8s-02-macro-architecture",
        "k8s-03-minikube-runtime",
        "k8s-04-objects-kubectl",
        "k8s-05-pod-workload",
        "k8s-06-deployment-rs",
        "k8s-07-daemon-stateful-job",
        "k8s-08-hpa-cri-crd",
        "k8s-09-service-l4",
        "k8s-10-network-dns",
        "k8s-11-pv-pvc",
        "k8s-12-secret-configmap",
        "k8s-13-ingress-l7",
        "k8s-14-gateway-api",
        "k8s-15-release-strategies",
        "k8s-16-prometheus-hpa",
        "k8s-17-custom-metrics",
        "k8s-18-logging-elk-efk",
        "k8s-19-jvm-in-container",
        "k8s-20-deploy-kubeadm-ha",
        "k8s-21-deploy-methods",
        "k8s-22-os-runtimes",
        "k8s-23-sandbox-runtimes",
        "k8s-24-storage-longhorn-glusterfs",
        "k8s-25-harbor-springcloud",
        "k8s-26-jenkins-canary",
        "k8s-27-advanced-rollout",
        "k8s-28-app-onboarding",
        "k8s-29-advanced-network",
        "k8s-30-service-mesh-istio",
        "k8s-31-keda-monitoring",
        "k8s-32-etcd-listwatch",
        "k8s-33-rbac-security",
        "k8s-34-crd-operator",
        "k8s-35-dra-gpu-scheduling",
      ],
    },
    {
      text: "DevOps / GitOps",
      icon: "gears",
      prefix: "devops/",
      collapsible: true,
      children: [
        "devops-01-what-is-devops",
        "devops-02-gitops",
        "devops-03-ci-basics",
        "devops-04-jenkins-pipeline",
        "devops-05-github-actions",
        "devops-06-sonarqube",
        "devops-07-harbor-ci",
        "devops-08-env-planning",
        "devops-09-argocd-install",
        "devops-10-argocd-ops",
        "devops-11-app-manifests",
        "devops-12-gitlab-ci-argocd",
        "devops-13-github-actions-argocd",
        "devops-14-jenkins-argocd",
        "devops-15-multicluster-rollback",
      ],
    },
    {
      text: "Serverless",
      icon: "cloud",
      prefix: "serverless/",
      collapsible: true,
      children: [
        "serverless-01-使用knative平台环境说明",
        "serverless-02-concepts",
        "serverless-06-knative介绍",
        "serverless-07-knative在云原生应用领域的定位",
        "serverless-08-knative与云原生平台的三个最佳实践",
        "serverless-09-knative-serving",
        "serverless-10-knative-eventing",
        "serverless-11-kn工具安装及应用",
        "serverless-12-knative-eventing组件及应用案例",
        "serverless-13-tekton安装",
        "serverless-14-tekton初体验",
        "serverless-15-构建自定义tag镜像应用案例",
        "serverless-16-tekton流水线中使用workspace应用案例",
        "serverless-17-使用-tekton-sidecar-实现-docker-in-docker-构建",
        "serverless-18-gitlab-触发-tekton-任务构建",
        "serverless-19-使用-tekton-实现自动化流水线",
        "serverless-20-tekton-与-argo-cd-结合实现-gitops",
        "serverless-21-knative-可观测性-使用prometheus与grafana监控",
        "serverless-22-efk",
        "serverless-23-openfaas-函数即服务",
        "serverless-24-云上serverless之aws-lambda",
        "serverless-25-serverless-framework与云上iac工具链",
        "serverless-26-serverless选型对比云上faas-vs-自建k8s",
      ],
    },
    {
      text: "可观测性",
      icon: "eye",
      prefix: "observability/",
      collapsible: true,
      children: [
        "observability-01-如何通过opentelemetry实现云原生应用全链路状态跟踪",
        "observability-02-prometheus安装",
        "observability-03-grafana对接prometheus数据源",
        "observability-04-prometheus告警alertmanager组件",
        "observability-05-prometheus告警媒介-企业微信",
        "observability-06-prometheus告警媒介-钉钉",
        "observability-07-容器化构建prometheus监控系统",
        "observability-08-容器监控方案-cadvisor",
        "observability-09-k8s监控方案-ksm-kube-state-metrics",
        "observability-11-helm部署prometheus及应用",
        "observability-12-如何通过pixie实现kubernetes云原生应用可观测",
        "observability-13-prom-ch1-开篇与学习路径",
        "observability-14-prom-ch2-学习目标",
        "observability-15-prom-ch3-安装与上手",
        "observability-16-prom-ch4-基本概念",
        "observability-17-prom-ch5-node_exporter",
        "observability-18-prom-ch6-PromQL-基础",
        "observability-19-prom-ch7-服务发现与-Relabel",
        "observability-20-prom-ch8-mysqld_exporter",
        "observability-21-prom-ch9-process-exporter",
        "observability-22-prom-ch10-redis-exporter",
        "observability-23-prom-ch11-KafkaZK-JVM-监控",
        "observability-24-prom-ch12-Pushgateway",
        "observability-25-prom-ch13-Alertmanager",
        "observability-26-prom-ch14-K8s-监控复杂度",
        "observability-27-prom-ch15-K8s-监控组件部署",
        "observability-28-prom-ch16-容器与-cAdvisor",
        "observability-29-prom-ch17-kube-state-metrics",
        "observability-30-prom-ch18-APIServer-监控",
        "observability-31-prom-ch19-自定义指标",
        "observability-32-prom-ch20-监控体系综述",
        "observability-33-prom-ch21-etcd-TLS",
        "observability-34-prom-ch22-K8s-服务发现",
        "observability-35-prom-ch23-Relabel-实战",
        "observability-36-prom-ch24-Target-与高基数",
        "observability-37-prom-ch25-高基数与采集端",
        "observability-38-prom-ch26-客户端指标类型",
        "observability-39-prom-ch27-动态分片",
        "observability-40-prom-ch28-分片项目实战",
        "observability-41-prom-ch29-日志转指标",
        "observability-42-prom-ch30-存储与-WAL",
        "observability-43-prom-ch31-压缩算法",
        "observability-44-prom-ch32-TSDB-索引与-Compact",
        "observability-45-prom-ch33-联邦与-Remote",
        "observability-46-prom-ch34-M3DB",
        "observability-47-prom-ch35-Thanos",
        "observability-48-prom-ch36-kube-prometheus",
        "observability-49-prom-ch37-HTTP-API",
        "observability-50-prom-ch38-Range-Query",
        "observability-51-prom-ch39-资源利用率报表",
        "observability-52-prom-ch40-配置与-confd",
        "observability-53-prom-ch41-告警源码",
        "observability-54-prom-ch42-告警高可用",
        "observability-55-prom-ch43-Alertmanager-流水线",
        "observability-56-prom-ch44-综合实战",
        "observability-57-prom-ch0-其他",
      ],
    },
    {
      text: "平台与实战",
      icon: "layer-group",
      prefix: "platform/",
      collapsible: true,
      children: [
        "platform-01-在linux上以all-in-one模式安装kubernetes-kubesphere",
        "platform-02-在kubernetes集群上最小化安装kubesphere",
        "platform-03-kubesphere-3-4-0-抢鲜版",
        "platform-04-kubesphere中集成apisix",
        "platform-05-kubesphere集成本地容器镜像仓库-harbor",
        "platform-06-kubesphere部署三高商城组织架构说明",
        "platform-07-微服务项目-基于kubernetes集群paas云平台-kubesphere部署",
        "platform-08-kubesphere多租户系统应用",
        "platform-09-openeelb部署及应用",
        "platform-10-kubernetes集群中部署服务思路",
        "platform-11-k8s集群中部署服务之应用环境配置",
        "platform-12-k8s集群中部署服务之dockerfile文件准备",
        "platform-13-k8s集群中部署服务之部署描述文件准备",
        "platform-14-k8s集群中部署项目之流水线",
        "platform-15-k8s集群中部署项目之数据库准备",
        "platform-16-k8s集群中流水线部署微服务",
        "platform-17-k8s集群中部署微服务项目前端代理服务-nginx",
        "platform-18-k8s集群中部署微服务vue",
        "platform-19-kubernetes集群公共服务-dns",
        "platform-20-coredns级联本地dns服务器",
        "platform-21-kubernetes集群公共服务-harbor",
        "platform-22-微服务部署前中间件部署",
        "platform-23-严选项目代码获取",
        "platform-24-严选商城项目部署前配置说明",
        "platform-25-严选商城项目部署前配置及数据库导入说明",
        "platform-26-严选项目流水线基础环境准备",
        "platform-27-严选商城项目部署前流水线编写",
        "platform-28-如何使用terraform实现对kubernetes集群中资源对象进行管理",
        "platform-29-如何通过cilium-cluster-mesh实现kubernetes多集群方案",
        "platform-30-kubernetes集群舰队管理-kurator",
        "platform-31-karmada部署及应用",
        "platform-32-kubernetes集群备份与恢复管理利器velero",
        "platform-33-阿里云容器服务-ack",
        "platform-34-k8s-1-22-版本集群部署",
        "platform-35-云原生边缘计算-kubeedge-部署",
      ],
    },
    {
      text: "扩展专题",
      icon: "puzzle-piece",
      prefix: "extend/",
      collapsible: true,
      children: [
        "extend-01-笔记-大数据hdfs分布式文件系统搭建",
        "extend-02-笔记-flink基于kubernetes部署",
        "extend-03-笔记-spark与kubernetes整合",
        "extend-04-基于k8s构建机器学习平台kubeflow",
        "extend-05-基于k8s构建云原生基础设施平台-kubeblocks",
        "extend-06-kubernetes管理虚拟机利器kubevirt",
        "extend-07-windows主机中构建适用于k8s-operator开发环境",
        "extend-08-almalinux-9操作系统",
        "extend-09-kubeadm极速部署kubernetes-1-29版本集群",
        "extend-10-kubernetes-2024-03-更新-kubernetes面试题",
      ],
    },
    {
      text: "Golang",
      icon: "golang",
      prefix: "golang/",
      collapsible: true,
      children: [
        "golang-01-overview",
        "golang-02-gin-parts",
        "golang-03-basics-units",
      ],
    },
  ],
  "/中间件/": [
    "",
    {
      text: "RabbitMQ",
      icon: "envelope",
      prefix: "rabbitmq/",
      collapsible: true,
      children: [
        "rabbitmq-01-what-is-mq",
        "rabbitmq-02-install-concepts",
        "rabbitmq-03-programming-model",
        "rabbitmq-04-queue-concepts",
        "rabbitmq-05-messaging-patterns",
        "rabbitmq-06-springboot",
        "rabbitmq-07-queue-types",
        "rabbitmq-08-dlx-delay",
        "rabbitmq-09-sharding",
        "rabbitmq-10-monitor-backup-federation",
        "rabbitmq-11-cluster-ha",
        "rabbitmq-11a-erlang-cookie",
        "rabbitmq-12-classic-backlog-degradation",
        "rabbitmq-13-amqp-and-protocols",
        "rabbitmq-14-networking",
        "rabbitmq-15-security",
        "rabbitmq-16-virtual-hosts",
        "rabbitmq-17-rpc",
        "rabbitmq-18-shovel",
        "rabbitmq-19-plugins",
        "rabbitmq-20-peer-discovery",
        "rabbitmq-21-migration-upgrade",
        "rabbitmq-22-production-checklist",
      ],
    },
    {
      text: "Kafka",
      icon: "diagram-project",
      prefix: "kafka/",
      collapsible: true,
      children: [
        "kafka-01-intro",
        "kafka-02-quickstart",
        "kafka-03-topic-partition-broker",
        "kafka-04-client-flow",
        "kafka-05-client-mechanisms",
        "kafka-06-springboot",
        "kafka-07-zk-controller",
        "kafka-08-leader-hw",
        "kafka-09-log-index",
        "kafka-10-io-offset",
        "kafka-11-extensions",
      ],
    },
    {
      text: "RocketMQ",
      icon: "rocket",
      prefix: "rocketmq/",
      collapsible: true,
      children: [
        "rocketmq-00-roadmap",
        "rocketmq-01-quickstart",
        "rocketmq-02-architecture",
        "rocketmq-03-client-model",
        "rocketmq-04-springboot-tips",
        "rocketmq-05-source-setup",
        "rocketmq-06-send-consume-lb",
        "rocketmq-07-persistence",
        "rocketmq-08-delay-longpolling",
        "rocketmq-09-zerocopy",
        "rocketmq-10-cluster-advanced",
      ],
    },
    {
      text: "MQ 常见问题",
      icon: "circle-question",
      prefix: "faq/",
      collapsible: true,
      children: [
        "mq-faq-01-no-loss",
        "mq-faq-02-common-issues",
      ],
    },
    {
      text: "Redis",
      icon: "database",
      prefix: "redis/",
      collapsible: true,
      children: [
        "redis-00-roadmap",
        "redis-01-install",
        "redis-02-data-structures",
        "redis-03-threading",
        "redis-04-persistence",
        "redis-05-replication-sentinel",
        "redis-06-cluster",
        "redis-07-cache-design",
        "redis-08-stack",
        "redis-09-bottom-string-hash-list",
        "redis-10-bottom-set-zset",
      ],
    },
    {
      text: "ZooKeeper",
      icon: "sitemap",
      prefix: "zookeeper/",
      collapsible: true,
      children: [
        "zk-01-intro",
        "zk-02-client-scenarios",
        "zk-03-distributed-lock",
        "zk-04-leader-election",
        "zk-05-zab",
      ],
    },
    {
      text: "ShardingSphere",
      icon: "table",
      prefix: "shardingsphere/",
      collapsible: true,
      children: [
        "ss-01-intro",
        "ss-02-jdbc-quickstart",
        "ss-03-sharding-strategies",
        "ss-04-encrypt-rw",
        "ss-05-kernel",
        "ss-06-proxy",
        "ss-07-cosid",
      ],
    },
    {
      text: "Elasticsearch",
      icon: "magnifying-glass",
      prefix: "elasticsearch/",
      collapsible: true,
      children: [
        "es-01-overview",
        "es-02-install",
        "es-03-data-concepts",
        "es-04-query-dsl",
        "es-05-relevance-agg",
        "es-06-springboot-search",
        "es-07-pagination-analyzer",
        "es-08-cluster",
        "es-09-production",
        "es-10-elk-sync",
      ],
    },
    {
      text: "Netty",
      icon: "network-wired",
      prefix: "netty/",
      collapsible: true,
      children: [
        "netty-01-tcpip",
        "netty-02-bio-nio",
        "netty-03-epoll",
        "netty-04-components",
        "netty-05-pipeline",
        "netty-06-framework",
        "netty-07-thread-model",
        "netty-08-architecture",
      ],
    },
  ],
  "/并发编程/": [
    "",
    {
      text: "并发基础",
      icon: "book",
      prefix: "basics/",
      collapsible: true,
      children: [
        "juc-01-why-concurrency",
        "juc-02-wait-notify",
        "juc-03-design-patterns",
        "juc-04-jmm",
        "juc-05-cpu-cache",
      ],
    },
    {
      text: "异步编程",
      icon: "clock",
      prefix: "async/",
      collapsible: true,
      children: [
        "juc-06-future",
        "juc-07-completable-future",
        "juc-08-threadlocal",
      ],
    },
    {
      text: "锁与同步",
      icon: "lock",
      prefix: "lock/",
      collapsible: true,
      children: [
        "juc-09-cas",
        "juc-10-atomic",
        "juc-11-synchronized",
        "juc-12-juc-locks",
        "juc-13-aqs-reentrantlock",
        "juc-14-semaphore",
        "juc-15-latch-barrier",
      ],
    },
    {
      text: "并发容器",
      icon: "boxes-stacked",
      prefix: "collections/",
      collapsible: true,
      children: [
        "juc-16-concurrent-collections",
        "juc-17-blocking-queue",
        "juc-18-queue-selection",
      ],
    },
    {
      text: "线程池",
      icon: "gears",
      prefix: "pool/",
      collapsible: true,
      children: [
        "juc-19-thread-pool",
        "juc-20-reject-pitfalls",
        "juc-21-dynamic-params",
        "juc-22-forkjoin",
      ],
    },
    {
      text: "性能扩展",
      icon: "gauge-high",
      prefix: "performance/",
      collapsible: true,
      children: [
        "juc-23-disruptor",
        "juc-24-summary",
      ],
    },
  ],
  "/软件架构/": [
    "",
    {
      text: "入门与动机",
      icon: "book",
      prefix: "ddd-basics/",
      collapsible: true,
      children: [
        "ddd-01-what-is-ddd",
        "ddd-02-scrum-anemic",
        "ddd-03-solid-oo",
      ],
    },
    {
      text: "战略设计",
      icon: "sitemap",
      prefix: "ddd-strategy/",
      collapsible: true,
      children: [
        "ddd-04-concepts-bc",
        "ddd-05-microservice-split",
        "ddd-06-strategic-modeling",
        "ddd-07-ubiquitous-eventstorm",
      ],
    },
    {
      text: "战术与分层",
      icon: "layer-group",
      prefix: "ddd-tactics/",
      collapsible: true,
      children: [
        "ddd-08-layered-models",
        "ddd-09-domain-primitive",
        "ddd-10-hexagonal-new-app",
        "ddd-11-repository",
        "ddd-12-domain-layer",
        "ddd-13-application-interface",
      ],
    },
    {
      text: "落地实践",
      icon: "gears",
      prefix: "ddd-practice/",
      collapsible: true,
      children: [
        "ddd-14-cola-scaffold",
        "ddd-15-acl-summary",
      ],
    },
  ],
  "/性能调优/": [
    "",
    {
      text: "JVM",
      icon: "gears",
      prefix: "jvm/",
      collapsible: true,
      children: [
        "jvm-01-overview",
        "jvm-02-classloader",
        "jvm-03-memory-model",
        "jvm-04-object-allocation",
        "jvm-05-classfile-bytecode",
        "jvm-06-execution-engine",
        "jvm-07-parnew-cms",
        "jvm-08-g1-zgc",
        "jvm-09-tuning-tools",
        "jvm-10-constant-pool",
        "jvm-11-jdk17-features",
        "jvm-12-jdk17-gc",
      ],
    },
    {
      text: "Tomcat",
      icon: "server",
      prefix: "tomcat/",
      collapsible: true,
      children: [
        "tomcat-01-architecture",
        "tomcat-02-thread-tuning",
        "tomcat-03-classloader-hotdeploy",
        "tomcat-04-summary",
      ],
    },
  ],
  "/数据库/": [
    "",
    {
      text: "MySQL",
      icon: "database",
      prefix: "mysql/",
      collapsible: true,
      children: [
        "mysql-01-architecture",
        "mysql-02-index-structure",
        "mysql-03-explain",
        "mysql-04-index-opt-1",
        "mysql-05-index-opt-2",
        "mysql-06-transaction-lock",
        "mysql-07-mvcc-bufferpool",
        "mysql-08-innodb-logs",
        "mysql-09-mysql8-features",
        "mysql-10-replication-ha",
      ],
    },
  ],
  "/分布式/": [
    "",
    {
      text: "学习路线",
      icon: "map",
      prefix: "roadmap/",
      collapsible: true,
      children: [
        "distributed-tx-roadmap",
      ],
    },
    {
      text: "事务地基",
      icon: "database",
      prefix: "tx-basics/",
      collapsible: true,
      children: [
        "tx-basics-01-acid-anomalies",
        "tx-basics-02-isolation-mvcc",
        "tx-basics-03-innodb-logs",
        "tx-basics-04-spring-transaction",
        "tx-basics-05-local-tx-limit",
      ],
    },
    {
      text: "理论与协议",
      icon: "scale-balanced",
      prefix: "theory/",
      collapsible: true,
      children: [
        "theory-01-distributed-reality",
        "theory-02-cap",
        "theory-03-base-spectrum",
        "theory-04-dtp-2pc",
        "theory-05-3pc",
        "theory-06-mysql-xa",
        "theory-07-xa-cost",
      ],
    },
    {
      text: "Seata AT",
      icon: "network-wired",
      prefix: "seata-at/",
      collapsible: true,
      children: [
        "seata-at-01-roles-lifecycle",
        "seata-at-02-deploy-tc",
        "seata-at-03-integrate-app",
        "seata-at-04-two-phase",
        "seata-at-05-isolation",
        "seata-at-06-src-tm",
        "seata-at-07-src-xid",
        "seata-at-08-src-rm",
        "seata-at-09-src-tc",
        "seata-at-10-src-phase2",
      ],
    },
    {
      text: "Seata TCC",
      icon: "handshake",
      prefix: "seata-tcc/",
      collapsible: true,
      children: [
        "seata-tcc-01-try-confirm-cancel",
        "seata-tcc-02-three-issues",
        "seata-tcc-03-fence",
        "seata-tcc-04-source",
      ],
    },
    {
      text: "Saga",
      icon: "diagram-project",
      prefix: "saga/",
      collapsible: true,
      children: [
        "saga-01-theory",
        "saga-02-orchestration-choreography",
        "saga-03-statemachine",
        "saga-04-selection",
      ],
    },
    {
      text: "消息一致性",
      icon: "envelope",
      prefix: "message/",
      collapsible: true,
      children: [
        "message-01-two-inconsistencies",
        "message-02-local-message-table",
        "message-03-rocketmq-tx",
        "message-04-idempotent-consume",
        "message-05-best-effort",
        "message-06-compare",
      ],
    },
    {
      text: "共识算法",
      icon: "vote-yea",
      prefix: "consensus/",
      collapsible: true,
      children: [
        "consensus-01-replication-quorum",
        "consensus-02-basic-paxos",
        "consensus-03-multi-paxos",
        "consensus-04-raft-election",
        "consensus-05-raft-log",
        "consensus-06-raft-safety",
        "consensus-07-etcd-lab",
        "consensus-08-seata-raft",
        "consensus-09-gossip-model",
        "consensus-10-swim-redis",
      ],
    },
    {
      text: "毕业实战",
      icon: "graduation-cap",
      prefix: "capstone/",
      collapsible: true,
      children: [
        "capstone-01-decision-tree",
        "capstone-02-final-project",
        "capstone-03-self-check",
      ],
    },
    {
      text: "Seata（早期系列）",
      icon: "network-wired",
      prefix: "seata/",
      collapsible: true,
      children: [
        "seata-01-distributed-tx-overview",
        "seata-02-at-mode",
        "seata-03-tc-server",
        "seata-04-at-tm-rm",
        "seata-05-tcc-practice",
        "seata-06-tcc-issues",
        "seata-07-tcc-source",
        "seata-08-isolation-interview",
      ],
    },
  ],
  "/微服务/": [
    "",
    {
      text: "Spring Boot",
      icon: "leaf",
      prefix: "springboot/",
      collapsible: true,
      children: [
        "boot-01-handwritten-core",
        "boot-02-startup-source",
        "boot-03-autoconfigure",
      ],
    },
    {
      text: "Spring Cloud Alibaba",
      icon: "cloud",
      prefix: "springcloud/",
      collapsible: true,
      children: [
        "sca-01-microservice-overview",
        "sca-02-practice-summary",
      ],
    },
    {
      text: "Nacos",
      icon: "sitemap",
      prefix: "nacos/",
      collapsible: true,
      children: [
        "nacos-01-architecture",
        "nacos-02-grpc",
        "nacos-03-config-center",
      ],
    },
    {
      text: "Sentinel",
      icon: "shield-halved",
      prefix: "sentinel/",
      collapsible: true,
      children: [
        "sentinel-01-architecture",
      ],
    },
    {
      text: "Seata 内核",
      icon: "database",
      prefix: "seata/",
      collapsible: true,
      children: [
        "seata-kernel-01-source",
      ],
    },
    {
      text: "Spring 扩展",
      icon: "puzzle-piece",
      prefix: "spring-ext/",
      collapsible: true,
      children: [
        "spring-ext-01-extension-points",
      ],
    },
    {
      text: "路线与占位",
      icon: "map",
      prefix: "roadmap/",
      collapsible: true,
      children: [
        "ms-12-roadmap-placeholders",
      ],
    },
  ],
  "/源码剖析/": [
    "",
    {
      text: "Spring 6 源码",
      icon: "leaf",
      prefix: "spring6/",
      collapsible: true,
      children: [
        "s6-01-compile",
        "s6-02-overview",
        "s6-03-components",
        "s6-04-handwritten",
        "s6-05-ioc-load",
        "s6-06-config-class",
        "s6-07-circular-dep",
        "s6-08-async-bean",
        "s6-09-bean-postprocessor",
        "s6-10-aop",
        "s6-11-transaction",
        "s6-12-event",
        "s6-13-extension-points",
        "s6-14-mybatis",
        "s6-15-aot",
        "s6-16-mvc-flow",
        "s6-17-mvc-parent-child",
      ],
    },
    {
      text: "MyBatis",
      icon: "database",
      prefix: "mybatis/",
      collapsible: true,
      children: [
        "mb-01-intro-basic",
        "mb-02-config",
        "mb-03-xml-params-result",
        "mb-04-xml-result-map",
        "mb-05-xml-dynamic-sql",
        "mb-06-xml-cache",
        "mb-07-generator-pagehelper",
        "mb-08-ssm",
        "mb-09-mybatis-plus",
        "mb-18-config-parse",
        "mb-19-sql-exec-flow",
      ],
    },
  ],
  "/微信小程序/": [
    "",
    {
      text: "小程序基础",
      icon: "weixin",
      prefix: "basics/",
      collapsible: true,
      children: [
        "mp-01-what-is-miniprogram",
        "mp-02-first-miniprogram",
        "mp-03-page-files-databinding",
        "mp-04-dual-thread-setdata",
        "mp-05-events",
        "mp-06-routing-page-stack",
        "mp-07-lifecycle",
        "mp-08-wxs",
        "mp-09-builtin-components",
        "mp-10-custom-components",
        "mp-11-api-permissions",
        "mp-12-skyline-glass-easel",
        "mp-13-subpackages-performance",
        "mp-14-publish",
      ],
    },
    {
      text: "小程序实战",
      icon: "list-check",
      prefix: "practice/",
      collapsible: true,
      children: [
        "td-01-create-project",
        "td-02-list-page",
        "td-03-add-toggle",
        "td-04-delete-component",
        "td-05-storage-ship",
      ],
    },
  ],
  "/前端/": [
    "",
    {
      text: "React TodoList 实战",
      icon: "list-check",
      prefix: "react-todolist/",
      collapsible: true,
      children: [
        "web-td-01-what-is-frontend",
        "web-td-02-create-vite-project",
        "web-td-03-types-and-state",
        "web-td-04-build-ui",
        "web-td-05-localstorage",
        "web-td-06-styles",
        "web-td-07-components",
        "web-td-08-run-build",
        "web-td-09-push-github",
        "web-td-10-deploy-pages",
      ],
    },
  ],
  "/亿级规模系统/": [
    "",
    {
      text: "学习总纲",
      icon: "map",
      prefix: "roadmap/",
      collapsible: true,
      children: [
        "scale-00-roadmap",
      ],
    },
    {
      text: "度量与估算",
      icon: "ruler",
      prefix: "metrics/",
      collapsible: true,
      children: [
        "metrics-01-traffic-language",
        "metrics-02-capacity-estimation",
        "metrics-03-message-anatomy",
      ],
    },
    {
      text: "接入层扩展",
      icon: "door-open",
      prefix: "access/",
      collapsible: true,
      children: [
        "access-01-scale-up-out",
        "access-02-load-balancing",
        "access-03-gateway",
        "access-04-thread-model",
        "access-05-benchmark-basics",
      ],
    },
    {
      text: "缓存体系",
      icon: "bolt",
      prefix: "cache/",
      collapsible: true,
      children: [
        "cache-01-db-first-victim",
        "cache-02-read-write-split",
        "cache-03-cache-patterns",
        "cache-04-three-brothers",
        "cache-05-consistency",
        "cache-06-hotkey-multilevel",
      ],
    },
    {
      text: "异步与消息",
      icon: "envelope",
      prefix: "async/",
      collapsible: true,
      children: [
        "async-01-sync-ceiling",
        "async-02-peak-shaving",
        "async-03-storage-model",
        "async-04-order-idempotent",
        "async-05-backlog",
        "async-06-push-pull",
        "async-07-mq-selection",
      ],
    },
    {
      text: "分库分表",
      icon: "table-cells",
      prefix: "sharding/",
      collapsible: true,
      children: [
        "sharding-01-before-split",
        "sharding-02-vertical-split",
        "sharding-03-horizontal-shardkey",
        "sharding-04-global-id",
        "sharding-05-cross-shard",
        "sharding-06-shardingsphere-migration",
      ],
    },
    {
      text: "流量防护",
      icon: "shield-halved",
      prefix: "protection/",
      collapsible: true,
      children: [
        "protection-01-avalanche",
        "protection-02-rate-limit-algorithms",
        "protection-03-cluster-limit",
        "protection-04-circuit-breaking",
        "protection-05-bulkhead-adaptive",
        "protection-06-sentinel",
      ],
    },
    {
      text: "高可用",
      icon: "heart-pulse",
      prefix: "ha/",
      collapsible: true,
      children: [
        "ha-01-nines",
        "ha-02-redundancy-failover",
        "ha-03-middleware-ha",
        "ha-04-multi-idc",
        "ha-05-chaos-drill",
      ],
    },
    {
      text: "亿级场景实战",
      icon: "diagram-project",
      prefix: "scenarios/",
      collapsible: true,
      children: [
        "scenarios-01-im",
        "scenarios-02-feed",
        "scenarios-03-push",
        "scenarios-04-seckill",
      ],
    },
    {
      text: "压测与容量",
      icon: "gauge-high",
      prefix: "pressure/",
      collapsible: true,
      children: [
        "pressure-01-fulllink",
        "pressure-02-shadow",
        "pressure-03-observability",
        "pressure-04-capacity-cost",
      ],
    },
    {
      text: "毕业设计",
      icon: "graduation-cap",
      prefix: "capstone/",
      collapsible: true,
      children: [
        "capstone-01-methodology",
        "capstone-02-final-project",
        "capstone-03-self-check",
      ],
    },
  ],
  "/web3区块链/": [
    "",
    {
      text: "学习路线",
      icon: "map",
      prefix: "roadmap/",
      collapsible: true,
      children: [
        "web3-00-roadmap",
      ],
    },
    {
      text: "地基与密码学",
      icon: "key",
      prefix: "00-foundations/",
      collapsible: true,
      children: [
        "foundations-01-why-blockchain",
        "foundations-02-hash-merkle",
        "foundations-03-keys-signatures",
        "foundations-04-wallets",
        "foundations-05-mini-blockchain",
      ],
    },
    {
      text: "比特币",
      icon: "coins",
      prefix: "01-bitcoin/",
      collapsible: true,
      children: [
        "bitcoin-01-utxo",
        "bitcoin-02-pow",
        "bitcoin-03-script",
        "bitcoin-04-tradeoffs",
      ],
    },
    {
      text: "以太坊核心",
      icon: "microchip",
      prefix: "02-evm/",
      collapsible: true,
      children: [
        "evm-01-accounts",
        "evm-02-transactions",
        "evm-03-evm-gas",
        "evm-04-nodes-rpc",
        "evm-05-storage",
      ],
    },
    {
      text: "Solidity 与 Foundry",
      icon: "code",
      prefix: "03-solidity/",
      collapsible: true,
      children: [
        "solidity-01-foundry-setup",
        "solidity-02-syntax-basics",
        "solidity-03-data-location",
        "solidity-04-mappings-events",
        "solidity-05-oop",
        "solidity-06-payable-eth",
        "solidity-07-testing",
        "solidity-08-deploy-verify",
      ],
    },
    {
      text: "代币标准",
      icon: "gem",
      prefix: "04-tokens/",
      collapsible: true,
      children: [
        "tokens-01-erc20",
        "tokens-02-erc721-1155",
        "tokens-03-erc4626",
        "tokens-04-upgradeable",
        "tokens-05-patterns",
      ],
    },
    {
      text: "DApp 全栈",
      icon: "laptop-code",
      prefix: "05-dapp/",
      collapsible: true,
      children: [
        "dapp-01-viem",
        "dapp-02-wallet-connect",
        "dapp-03-frontend-dapp",
        "dapp-04-graph",
        "dapp-05-storage",
      ],
    },
    {
      text: "安全攻防",
      icon: "shield-halved",
      prefix: "06-security/",
      collapsible: true,
      children: [
        "security-01-threat-model",
        "security-02-reentrancy",
        "security-03-access-control",
        "security-04-arithmetic-oracle",
        "security-05-mev",
        "security-06-tools",
        "security-07-audit-method",
      ],
    },
    {
      text: "DeFi 协议",
      icon: "chart-line",
      prefix: "07-defi/",
      collapsible: true,
      children: [
        "defi-01-landscape",
        "defi-02-amm",
        "defi-03-lending",
        "defi-04-stablecoins",
        "defi-05-oracles-chainlink",
        "defi-06-staking-restaking",
        "defi-07-governance-dao",
        "defi-08-tokenomics",
      ],
    },
    {
      text: "共识与扩容",
      icon: "layer-group",
      prefix: "08-l2/",
      collapsible: true,
      children: [
        "l2-01-pos-consensus",
        "l2-02-scaling-roadmap",
        "l2-03-optimistic-rollup",
        "l2-04-zk-rollup",
        "l2-05-bridges",
        "l2-06-account-abstraction",
      ],
    },
    {
      text: "生态与毕业",
      icon: "graduation-cap",
      prefix: "09-capstone/",
      collapsible: true,
      children: [
        "capstone-01-multichain",
        "capstone-02-rwa",
        "capstone-03-final-project",
        "capstone-04-self-check",
      ],
    },
  ],
  "/tag/": false,
  "/category/": false,
  "/article/": false,
  "/star/": false,
  "/timeline/": false,
});
