import { sidebar } from "vuepress-theme-hope";

// 由 scripts/gen-sidebar.mjs 自动生成，请勿手改。
// 新增分类：直接建子文件夹；权限书稿可在分类下再建卷目录（二级侧栏）。
// 新增文章：放入对应文件夹并写 shortTitle / order / sidebarGroup
// icon / 显示名 / 分类顺序可在 scripts/sidebar/<模块>.mjs 里覆盖
// 然后运行：pnpm sidebar:gen
export default sidebar({
  "/Ai/": [
    "",
    {
      text: "自动化 / Playwright",
      icon: "robot",
      prefix: "playwright/",
      collapsible: true,
      children: [
        "playwright-cli-learn",
        "playwright-Agent-Skills",
        "playwright-Agent-Skills-Ai-News",
        "LangChain-Learn",
      ],
    },
    {
      text: "RAG / LangChain",
      icon: "book",
      prefix: "rag/",
      collapsible: true,
      children: [
        "langchain-rag",
      ],
    },
    {
      text: "本地模型",
      icon: "server",
      prefix: "local-llm/",
      collapsible: true,
      children: [
        "ollama-opencode-local-llm",
        "qwen3-5-27b-deep-dive",
      ],
    },
    {
      text: "Agent / 方法论",
      icon: "lightbulb",
      prefix: "agent/",
      collapsible: true,
      children: [
        "how-to-build-tech-info-radar",
        "harness-engineering",
        "2026年AI-Agent框架选型指南：从“大爆发”到“大灭绝”后的生存法则",
      ],
    },
    {
      text: "基础知识",
      icon: "book",
      prefix: "基础知识/",
      collapsible: true,
      children: [
        "harness-engineering",
      ],
    },
    {
      text: "Spring AI",
      icon: "robot",
      prefix: "spring-ai/",
      collapsible: true,
      children: [
        "sai-01-features",
        "sai-02-quickstart",
        "sai-03-chatclient",
        "sai-04-prompt",
        "sai-05-advisor",
        "sai-06-memory",
        "sai-07-structured-tools",
        "sai-08-function-call",
        "sai-09-mcp",
        "sai-10-rag",
        "sai-11-airline-rag",
        "sai-12-knowledge-base",
        "sai-13-rag-eval",
        "sai-14-observability",
        "sai-15-agent-patterns",
        "sai-16-v11-update",
      ],
    },
    {
      text: "Spring AI Alibaba",
      icon: "robot",
      prefix: "spring-ai-alibaba/",
      collapsible: true,
      children: [
        "saa-01-know-agent",
        "saa-02-quickstart",
        "saa-03-deep-usage",
        "saa-04-hooks-interceptors",
        "saa-05-skills",
        "saa-05b-xiaolongxia",
        "saa-06-multi-agent",
        "saa-07-graph-hr",
      ],
    },
  ],
  "/BigData/": [
    "",
    {
      text: "Hadoop 系列",
      icon: "database",
      prefix: "hadoop-series/",
      collapsible: true,
      children: [
        "hadoop-series-01-what-is-hadoop",
        "hadoop-series-02-hdfs-core-concepts",
        "hadoop-series-03-hdfs-read-write",
        "hadoop-series-04-mapreduce",
        "hadoop-series-05-yarn",
        "hadoop-series-06-hive",
        "hadoop-series-07-kafka-hadoop",
        "hadoop-series-08-hbase",
        "hadoop-series-09-data-warehouse",
        "hadoop-series-10-future",
      ],
    },
    {
      text: "实战与概念",
      icon: "flask",
      prefix: "practice/",
      collapsible: true,
      children: [
        "hadoop-docker-wordcount-demo",
        "lambda-kappa-architecture-concepts",
      ],
    },
  ],
  "/DotNet/": [
    "",
    {
      text: "ASP.NET Core",
      icon: "code",
      prefix: "aspnetcore/",
      collapsible: true,
      children: [
        "1-kestrel-socket-connection-listener",
        "2-aspnetcore-request-pipeline-debug",
        "3-aspnetcore-10-source-map",
        "4-aspnetcore-10-source-build-retrospective",
      ],
    },
  ],
  "/Java/": [
    "",
    {
      text: "源码调试",
      icon: "code",
      prefix: "source-debug/",
      collapsible: true,
      children: [
        "mybatis-source-debug-setup",
      ],
    },
  ],
  "/Windows/": [
    "",
    {
      text: "权限",
      icon: "shield-halved",
      prefix: "permissions/",
      collapsible: true,
      children: [
        "00-index",
        {
          text: "卷一·发明权限",
          icon: "book",
          prefix: "vol1-invent/",
          collapsible: true,
          children: [
            "01-no-permission",
            "02-account",
            "03-sid",
            "04-name-sid-lsa",
            "05-logon-lsa",
            "06-access-token",
            "07-owner",
            "08-permission-bits",
            "09-groups",
            "10-ace-dacl",
            "11-access-check",
            "12-security-descriptor",
            "13-inheritance",
            "14-effective-permissions",
            "15-sacl",
          ],
        },
        {
          text: "卷二·网上的身份",
          icon: "book",
          prefix: "vol2-identity/",
          collapsible: true,
          children: [
            "01-domain-dc",
            "02-kerberos",
            "03-ntlm",
            "04-logon-types",
            "05-spn",
          ],
        },
        {
          text: "卷三·权利与 UAC",
          icon: "book",
          prefix: "vol3-rights-uac/",
          collapsible: true,
          children: [
            "01-rights-uac",
            "02-user-rights",
            "03-uac",
            "04-gpo-rights",
            "05-adminsdholder",
          ],
        },
        {
          text: "卷四·不只是文件",
          icon: "book",
          prefix: "vol4-beyond-files/",
          collapsible: true,
          children: [
            "01-registry",
            "02-services",
            "03-ad-delegation",
          ],
        },
        {
          text: "卷五·排障与设计",
          icon: "book",
          prefix: "vol5-ops/",
          collapsible: true,
          children: [
            "01-share-design",
            "02-effective-access-practice",
            "03-troubleshooting-cases",
          ],
        },
        {
          text: "卷六·用代码改权限",
          icon: "book",
          prefix: "vol6-dotnet/",
          collapsible: true,
          children: [
            "01-identity",
            "02-acl",
            "03-impersonation",
          ],
        },
        {
          text: "附录",
          icon: "book",
          prefix: "appendix/",
          collapsible: true,
          children: [
            "01-map",
            "02-sddl",
            "03-event-ids",
            "04-lab",
            "05-references",
          ],
        },
        {
          text: "卷七·安全防护",
          icon: "folder",
          prefix: "vol7-defense/",
          collapsible: true,
          children: [
            "01-windows-hello",
            "02-credential-guard",
            "03-vbs-hvci",
            "04-app-control",
            "05-bitlocker",
          ],
        },
      ],
    },
    {
      text: "环境搭建",
      icon: "laptop-code",
      prefix: "setup/",
      collapsible: true,
      children: [
        "windows-wsl-docker-hadoop-setup",
        "fix-jekyll-build-on-windows",
      ],
    },
  ],
  "/Tools/": [
    "",
    {
      text: "编码与发布",
      icon: "file-code",
      prefix: "encoding-publish/",
      collapsible: true,
      children: [
        "Utf8_And_Unicode",
        "how-a-local-folder-gets-published-to-github",
      ],
    },
    {
      text: "Git / 代理",
      icon: "network-wired",
      prefix: "git-proxy/",
      collapsible: true,
      children: [
        "git-proxy-internal-repo-fix",
        "clash-verge-tun-mode-git-ssh-fix",
      ],
    },
    {
      text: "其他工具",
      icon: "screwdriver-wrench",
      prefix: "misc/",
      collapsible: true,
      children: [
        "yt-dlp的使用",
      ],
    },
  ],
  "/English/": [
    "",
    {
      text: "语法",
      icon: "book",
      prefix: "grammar/",
      collapsible: true,
      children: [
        "all-tenses-learn-english",
      ],
    },
    {
      text: "论文生词",
      icon: "language",
      prefix: "vocabulary/",
      collapsible: true,
      children: [
        "eventual-consistency-b1-vocabulary",
      ],
    },
  ],
  "/Notes/": [
    "",
    {
      text: "HAMi",
      icon: "microchip",
      prefix: "hami/",
      collapsible: true,
      children: [
        "Hami",
        "Hami-Learning",
        "Hami-Use",
        "Hami-UseTo-Make-Money",
      ],
    },
    {
      text: "基础概念",
      icon: "lightbulb",
      prefix: "concepts/",
      collapsible: true,
      children: [
        "one-hot",
        "math-jax",
      ],
    },
    {
      text: "项目与工作流",
      icon: "diagram-project",
      prefix: "projects/",
      collapsible: true,
      children: [
        "zero-to-hero-auto-warehouse",
        "project-learning-map",
        "three-blog-skills-for-retrospective-and-publish",
        "hello-202026",
      ],
    },
    {
      text: "思考",
      icon: "folder",
      prefix: "think/",
      collapsible: true,
      children: [
        "技术专家10问自查清单",
      ],
    },
  ],
  "/云原生/": [
    "",
    {
      text: "云原生基础",
      icon: "seedling",
      prefix: "foundation/",
      collapsible: true,
      children: [
        "foundation-01-云原生",
        "foundation-02-虚拟化技术",
        "foundation-03-云计算",
      ],
    },
    {
      text: "Docker",
      icon: "cube",
      prefix: "docker/",
      collapsible: true,
      children: [
        "docker-01-what-is-docker",
        "docker-02-engine-platform",
        "docker-03-container-vs-vm",
        "docker-04-install",
        "docker-05-container-and-image",
        "docker-06-container-commands",
        "docker-07-enter-container",
        "docker-08-image-transfer",
        "docker-09-harbor",
        "docker-10-dockerfile",
        "docker-11-process-view",
        "docker-12-daemon-runtime",
        "docker-13-tech-foundation",
        "docker-14-unionfs",
        "docker-15-namespace",
        "docker-16-cgroups",
        "docker-17-network",
        "docker-18-compose",
        "docker-19-如何通过docker部署https访问的nginx应用",
        "docker-20-container-runtime-docker",
        "docker-21-轻量级容器管理工具-containerd",
      ],
    },
    {
      text: "Kubernetes",
      icon: "dharmachakra",
      prefix: "k8s/",
      collapsible: true,
      children: [
        "k8s-01-cloud-native",
        "k8s-02-macro-architecture",
        "k8s-03-minikube-runtime",
        "k8s-04-objects-kubectl",
        "k8s-05-pod-workload",
        "k8s-06-deployment-rs",
        "k8s-07-daemon-stateful-job",
        "k8s-08-hpa-cri-crd",
        "k8s-09-service-l4",
        "k8s-10-network-dns",
        "k8s-11-pv-pvc",
        "k8s-12-ingress-l7",
        "k8s-13-release-strategies",
        "k8s-14-service-mesh-istio",
        "k8s-15-harbor-springcloud",
        "k8s-16-secret-configmap",
        "k8s-17-jenkins-canary",
        "k8s-18-prometheus-hpa",
        "k8s-19-custom-metrics",
        "k8s-20-jvm-in-container",
      ],
    },
    {
      text: "K8s 运维笔记",
      icon: "screwdriver-wrench",
      prefix: "k8s-ops/",
      collapsible: true,
      children: [
        "k8s-ops-01-kubernetes配置与密钥管理-configmap-secret",
        "k8s-ops-02-kubernetes集群使用容器镜像仓库harbor",
        "k8s-ops-03-kubernetes集群公共服务",
        "k8s-ops-04-kubernetes集群java项目上云部署",
        "k8s-ops-05-kubernetes集群python项目上云部署",
        "k8s-ops-06-kubernetes集群golang项目上云部署",
        "k8s-ops-07-kubernetes日志收集方案-elk",
        "k8s-ops-08-kubernetes日志收集方案-efk",
        "k8s-ops-09-rocketmq部署",
        "k8s-ops-10-kubernetes集群包管理解决方案及应用商店-helm-kubeapps",
        "k8s-ops-11-安全容器运行时-kata",
        "k8s-ops-12-新型沙箱安全容器运行时-gvisor",
        "k8s-ops-13-如何使用kubernetes实现服务自动伸缩-hpa-vpa",
        "k8s-ops-14-如何基于事件驱动扩展k8s应用的深度实践",
        "k8s-ops-15-如何通过prometheus及hpa实现kubernetes应用自动水平伸缩",
        "k8s-ops-16-如何使用argo-rollouts实现金丝雀发布",
        "k8s-ops-17-原地升级及全链路灰度发布解决方案-openkruise",
        "k8s-ops-18-kubeadm极速部署kubernetes-1-24版本集群",
        "k8s-ops-19-kubeadm部署高可用kubernetes集群-1-21-0",
        "k8s-ops-20-使用rke构建企业生产kubernetes集群",
        "k8s-ops-21-kubernetes高可用集群二进制部署-runtime-docker",
        "k8s-ops-22-kubernetes集群ui及主机资源监控",
        "k8s-ops-23-使用sealos部署kubernetes集群并实现集群管理",
        "k8s-ops-24-debian-12部署k8s-1-28版集群",
        "k8s-ops-25-kubeadm极速部署kubernetes-1-27-1版本集群",
        "k8s-ops-26-基于cri-o实现k8s-1-28二进制高可用集群",
        "k8s-ops-27-基于docker实现k8s-1-28二进制高可用集群",
        "k8s-ops-28-kubespray部署k8s-1-26集群",
        "k8s-ops-29-kubernetes集群部署口袋工具-minikube",
        "k8s-ops-30-kubernetes介绍与集群架构",
        "k8s-ops-31-kubernetes集群部署方式说明",
        "k8s-ops-32-kubeadm部署单master节点kubernetes集群-1-21-0",
        "k8s-ops-33-kubeadm极速部署kubernetes-1-28版本集群",
        "k8s-ops-34-如何基于ubuntu-24-04部署原生k8s-1-31-0集群",
        "k8s-ops-35-k8s集群网络插件cilium-网络加速器-部署及使用验证",
        "k8s-ops-36-国产化openeuler-欧拉-操作系统部署k8s集群",
        "k8s-ops-37-国产化麒麟操作系统部署k8s",
        "k8s-ops-38-基于cri-o容器运行时部署k8s集群",
        "k8s-ops-39-基于docker部署k8s-1-28集群",
        "k8s-ops-40-基于openeuler操作系统使用isula容器运行时部署k8s集群",
        "k8s-ops-41-ubuntu-22-04部署k8s集群",
        "k8s-ops-42-ubuntu-23-04部署k8s集群",
        "k8s-ops-43-如何基于ubuntu-22-04部署原生k8s-1-29-0集群",
        "k8s-ops-44-如何通过kube-vip实现k8s集群高可用",
        "k8s-ops-45-kubeadm快速部署kubernetes-1-29-0版本集群",
        "k8s-ops-46-如何基于ubuntu-24-04部署原生k8s-1-30-0集群",
        "k8s-ops-47-如何通过k0s部署k8s二进制集群",
        "k8s-ops-48-rke2方式部署k8s集群-高可用",
        "k8s-ops-49-kubernetes集群客户端命令-kubectl",
        "k8s-ops-50-kubernetes集群node管理",
        "k8s-ops-51-kubernetes集群声明式文件yaml",
        "k8s-ops-52-kubernetes集群命名空间-namespace",
        "k8s-ops-53-kubernetes集群核心概念",
        "k8s-ops-54-kubernetes核心概念-pod",
        "k8s-ops-55-kubernetes核心概念-controller",
        "k8s-ops-56-kubernetes核心概念-controller控制器之statefulset",
        "k8s-ops-57-kubernetes核心概念-service",
        "k8s-ops-58-kubernetes集群-服务暴露-nginx-ingress-controller",
        "k8s-ops-59-ingress-nginx-controller-1-4-0-最新版本部署方法",
        "k8s-ops-60-基于ingress-nginx实现灰度发布系统",
        "k8s-ops-61-kubernetes集群服务暴露-traefik",
        "k8s-ops-62-kubernetes高可用集群二进制部署-runtime-containerd",
        "k8s-ops-63-k8s-1-26集群部署-容器运行时为containerd",
        "k8s-ops-64-基于containerd实现k8s-1-28二进制高可用集群",
        "k8s-ops-65-如何基于ubuntu-24-04部署原生k8s-1-32-0集群",
        "k8s-ops-66-基于containerd容器运行时部署k8s-1-28集群",
        "k8s-ops-67-k8s-1-26-underlay网络方案-hybridnet",
        "k8s-ops-68-k8s-1-22-版本双栈协议-ipv4-ipv6-集群部署",
        "k8s-ops-69-kubernetes持久化存储卷及存储动态供给",
        "k8s-ops-70-k8s集群存储解决方案-glusterfs",
        "k8s-ops-71-如何基于kubernetes使用分布式块存储longhorn",
      ],
    },
    {
      text: "DevOps / GitOps",
      icon: "gears",
      prefix: "devops/",
      collapsible: true,
      children: [
        "devops-01-devops",
        "devops-02-gitops",
        "devops-03-argocd部署指南",
        "devops-04-使用argo-cd实现流水线发布项目",
        "devops-05-使用argo-cd实施项目发布",
      ],
    },
    {
      text: "Serverless",
      icon: "cloud",
      prefix: "serverless/",
      collapsible: true,
      children: [
        "serverless-01-使用knative平台环境说明",
        "serverless-02-concepts",
        "serverless-06-knative介绍",
        "serverless-07-knative在云原生应用领域的定位",
        "serverless-08-knative与云原生平台的三个最佳实践",
        "serverless-09-knative-serving",
        "serverless-10-knative-eventing",
        "serverless-11-kn工具安装及应用",
        "serverless-12-knative-eventing组件及应用案例",
        "serverless-13-tekton安装",
        "serverless-14-tekton初体验",
        "serverless-15-构建自定义tag镜像应用案例",
        "serverless-16-tekton流水线中使用workspace应用案例",
        "serverless-17-使用-tekton-sidecar-实现-docker-in-docker-构建",
        "serverless-18-gitlab-触发-tekton-任务构建",
        "serverless-19-使用-tekton-实现自动化流水线",
        "serverless-20-tekton-与-argo-cd-结合实现-gitops",
        "serverless-21-knative-可观测性-使用prometheus与grafana监控",
        "serverless-22-efk",
        "serverless-23-openfaas-函数即服务",
      ],
    },
    {
      text: "可观测性",
      icon: "eye",
      prefix: "observability/",
      collapsible: true,
      children: [
        "observability-01-如何通过opentelemetry实现云原生应用全链路状态跟踪",
        "observability-02-prometheus安装",
        "observability-03-grafana对接prometheus数据源",
        "observability-04-prometheus告警alertmanager组件",
        "observability-05-prometheus告警媒介-企业微信",
        "observability-06-prometheus告警媒介-钉钉",
        "observability-07-容器化构建prometheus监控系统",
        "observability-08-容器监控方案-cadvisor",
        "observability-09-k8s监控方案-ksm-kube-state-metrics",
        "observability-11-helm部署prometheus及应用",
        "observability-12-如何通过pixie实现kubernetes云原生应用可观测",
        "observability-13-prom-ch1-开篇与学习路径",
        "observability-14-prom-ch2-学习目标",
        "observability-15-prom-ch3-安装与上手",
        "observability-16-prom-ch4-基本概念",
        "observability-17-prom-ch5-node_exporter",
        "observability-18-prom-ch6-PromQL-基础",
        "observability-19-prom-ch7-服务发现与-Relabel",
        "observability-20-prom-ch8-mysqld_exporter",
        "observability-21-prom-ch9-process-exporter",
        "observability-22-prom-ch10-redis-exporter",
        "observability-23-prom-ch11-KafkaZK-JVM-监控",
        "observability-24-prom-ch12-Pushgateway",
        "observability-25-prom-ch13-Alertmanager",
        "observability-26-prom-ch14-K8s-监控复杂度",
        "observability-27-prom-ch15-K8s-监控组件部署",
        "observability-28-prom-ch16-容器与-cAdvisor",
        "observability-29-prom-ch17-kube-state-metrics",
        "observability-30-prom-ch18-APIServer-监控",
        "observability-31-prom-ch19-自定义指标",
        "observability-32-prom-ch20-监控体系综述",
        "observability-33-prom-ch21-etcd-TLS",
        "observability-34-prom-ch22-K8s-服务发现",
        "observability-35-prom-ch23-Relabel-实战",
        "observability-36-prom-ch24-Target-与高基数",
        "observability-37-prom-ch25-高基数与采集端",
        "observability-38-prom-ch26-客户端指标类型",
        "observability-39-prom-ch27-动态分片",
        "observability-40-prom-ch28-分片项目实战",
        "observability-41-prom-ch29-日志转指标",
        "observability-42-prom-ch30-存储与-WAL",
        "observability-43-prom-ch31-压缩算法",
        "observability-44-prom-ch32-TSDB-索引与-Compact",
        "observability-45-prom-ch33-联邦与-Remote",
        "observability-46-prom-ch34-M3DB",
        "observability-47-prom-ch35-Thanos",
        "observability-48-prom-ch36-kube-prometheus",
        "observability-49-prom-ch37-HTTP-API",
        "observability-50-prom-ch38-Range-Query",
        "observability-51-prom-ch39-资源利用率报表",
        "observability-52-prom-ch40-配置与-confd",
        "observability-53-prom-ch41-告警源码",
        "observability-54-prom-ch42-告警高可用",
        "observability-55-prom-ch43-Alertmanager-流水线",
        "observability-56-prom-ch44-综合实战",
        "observability-57-prom-ch0-其他",
      ],
    },
    {
      text: "平台与实战",
      icon: "layer-group",
      prefix: "platform/",
      collapsible: true,
      children: [
        "platform-01-在linux上以all-in-one模式安装kubernetes-kubesphere",
        "platform-02-在kubernetes集群上最小化安装kubesphere",
        "platform-03-kubesphere-3-4-0-抢鲜版",
        "platform-04-kubesphere中集成apisix",
        "platform-05-kubesphere集成本地容器镜像仓库-harbor",
        "platform-06-kubesphere部署三高商城组织架构说明",
        "platform-07-微服务项目-基于kubernetes集群paas云平台-kubesphere部署",
        "platform-08-kubesphere多租户系统应用",
        "platform-09-openeelb部署及应用",
        "platform-10-kubernetes集群中部署服务思路",
        "platform-11-k8s集群中部署服务之应用环境配置",
        "platform-12-k8s集群中部署服务之dockerfile文件准备",
        "platform-13-k8s集群中部署服务之部署描述文件准备",
        "platform-14-k8s集群中部署项目之流水线",
        "platform-15-k8s集群中部署项目之数据库准备",
        "platform-16-k8s集群中流水线部署微服务",
        "platform-17-k8s集群中部署微服务项目前端代理服务-nginx",
        "platform-18-k8s集群中部署微服务vue",
        "platform-19-kubernetes集群公共服务-dns",
        "platform-20-coredns级联本地dns服务器",
        "platform-21-kubernetes集群公共服务-harbor",
        "platform-22-微服务部署前中间件部署",
        "platform-23-严选项目代码获取",
        "platform-24-严选商城项目部署前配置说明",
        "platform-25-严选商城项目部署前配置及数据库导入说明",
        "platform-26-严选项目流水线基础环境准备",
        "platform-27-严选商城项目部署前流水线编写",
        "platform-28-如何使用terraform实现对kubernetes集群中资源对象进行管理",
        "platform-29-如何通过cilium-cluster-mesh实现kubernetes多集群方案",
        "platform-30-kubernetes集群舰队管理-kurator",
        "platform-31-karmada部署及应用",
        "platform-32-kubernetes集群备份与恢复管理利器velero",
        "platform-33-阿里云容器服务-ack",
        "platform-34-k8s-1-22-版本集群部署",
        "platform-35-云原生边缘计算-kubeedge-部署",
      ],
    },
    {
      text: "扩展专题",
      icon: "puzzle-piece",
      prefix: "extend/",
      collapsible: true,
      children: [
        "extend-01-笔记-大数据hdfs分布式文件系统搭建",
        "extend-02-笔记-flink基于kubernetes部署",
        "extend-03-笔记-spark与kubernetes整合",
        "extend-04-基于k8s构建机器学习平台kubeflow",
        "extend-05-基于k8s构建云原生基础设施平台-kubeblocks",
        "extend-06-kubernetes管理虚拟机利器kubevirt",
        "extend-07-windows主机中构建适用于k8s-operator开发环境",
        "extend-08-almalinux-9操作系统",
        "extend-09-kubeadm极速部署kubernetes-1-29版本集群",
        "extend-10-kubernetes-2024-03-更新-kubernetes面试题",
      ],
    },
    {
      text: "Golang",
      icon: "golang",
      prefix: "golang/",
      collapsible: true,
      children: [
        "golang-01-overview",
        "golang-02-gin-parts",
        "golang-03-basics-units",
      ],
    },
  ],
  "/中间件/": [
    "",
    {
      text: "RabbitMQ",
      icon: "envelope",
      prefix: "rabbitmq/",
      collapsible: true,
      children: [
        "rabbitmq-01-what-is-mq",
        "rabbitmq-02-install-concepts",
        "rabbitmq-03-programming-model",
        "rabbitmq-04-queue-concepts",
        "rabbitmq-05-messaging-patterns",
        "rabbitmq-06-springboot",
        "rabbitmq-07-queue-types",
        "rabbitmq-08-dlx-delay",
        "rabbitmq-09-sharding",
        "rabbitmq-10-monitor-backup-federation",
        "rabbitmq-11-cluster-ha",
        "rabbitmq-12-classic-backlog-degradation",
        "rabbitmq-13-amqp-and-protocols",
        "rabbitmq-14-networking",
        "rabbitmq-15-security",
        "rabbitmq-16-virtual-hosts",
        "rabbitmq-17-rpc",
        "rabbitmq-18-shovel",
        "rabbitmq-19-plugins",
        "rabbitmq-20-peer-discovery",
        "rabbitmq-21-migration-upgrade",
        "rabbitmq-22-production-checklist",
      ],
    },
    {
      text: "Kafka",
      icon: "diagram-project",
      prefix: "kafka/",
      collapsible: true,
      children: [
        "kafka-01-intro",
        "kafka-02-quickstart",
        "kafka-03-topic-partition-broker",
        "kafka-04-client-flow",
        "kafka-05-client-mechanisms",
        "kafka-06-springboot",
        "kafka-07-zk-controller",
        "kafka-08-leader-hw",
        "kafka-09-log-index",
        "kafka-10-io-offset",
        "kafka-11-extensions",
      ],
    },
    {
      text: "RocketMQ",
      icon: "rocket",
      prefix: "rocketmq/",
      collapsible: true,
      children: [
        "rocketmq-01-quickstart",
        "rocketmq-02-architecture",
        "rocketmq-03-client-model",
        "rocketmq-04-springboot-tips",
        "rocketmq-05-source-setup",
        "rocketmq-06-send-consume-lb",
        "rocketmq-07-persistence",
        "rocketmq-08-delay-longpolling",
        "rocketmq-09-zerocopy",
        "rocketmq-10-cluster-advanced",
      ],
    },
    {
      text: "MQ 常见问题",
      icon: "circle-question",
      prefix: "faq/",
      collapsible: true,
      children: [
        "mq-faq-01-no-loss",
        "mq-faq-02-common-issues",
      ],
    },
    {
      text: "Redis",
      icon: "database",
      prefix: "redis/",
      collapsible: true,
      children: [
        "redis-01-install",
        "redis-02-data-structures",
        "redis-03-threading",
        "redis-04-persistence",
        "redis-05-replication-sentinel",
        "redis-06-cluster",
        "redis-07-cache-design",
        "redis-08-stack",
        "redis-09-bottom-string-hash-list",
        "redis-10-bottom-set-zset",
      ],
    },
    {
      text: "ZooKeeper",
      icon: "sitemap",
      prefix: "zookeeper/",
      collapsible: true,
      children: [
        "zk-01-intro",
        "zk-02-client-scenarios",
        "zk-03-distributed-lock",
        "zk-04-leader-election",
        "zk-05-zab",
      ],
    },
    {
      text: "ShardingSphere",
      icon: "table",
      prefix: "shardingsphere/",
      collapsible: true,
      children: [
        "ss-01-intro",
        "ss-02-jdbc-quickstart",
        "ss-03-sharding-strategies",
        "ss-04-encrypt-rw",
        "ss-05-kernel",
        "ss-06-proxy",
        "ss-07-cosid",
      ],
    },
    {
      text: "Elasticsearch",
      icon: "magnifying-glass",
      prefix: "elasticsearch/",
      collapsible: true,
      children: [
        "es-01-overview",
        "es-02-install",
        "es-03-data-concepts",
        "es-04-query-dsl",
        "es-05-relevance-agg",
        "es-06-springboot-search",
        "es-07-pagination-analyzer",
        "es-08-cluster",
        "es-09-production",
        "es-10-elk-sync",
      ],
    },
    {
      text: "Netty",
      icon: "network-wired",
      prefix: "netty/",
      collapsible: true,
      children: [
        "netty-01-tcpip",
        "netty-02-bio-nio",
        "netty-03-epoll",
        "netty-04-components",
        "netty-05-pipeline",
        "netty-06-framework",
        "netty-07-thread-model",
        "netty-08-architecture",
      ],
    },
  ],
  "/并发编程/": [
    "",
    {
      text: "并发基础",
      icon: "book",
      prefix: "basics/",
      collapsible: true,
      children: [
        "juc-01-why-concurrency",
        "juc-02-wait-notify",
        "juc-03-design-patterns",
        "juc-04-jmm",
        "juc-05-cpu-cache",
      ],
    },
    {
      text: "异步编程",
      icon: "clock",
      prefix: "async/",
      collapsible: true,
      children: [
        "juc-06-future",
        "juc-07-completable-future",
        "juc-08-threadlocal",
      ],
    },
    {
      text: "锁与同步",
      icon: "lock",
      prefix: "lock/",
      collapsible: true,
      children: [
        "juc-09-cas",
        "juc-10-atomic",
        "juc-11-synchronized",
        "juc-12-juc-locks",
        "juc-13-aqs-reentrantlock",
        "juc-14-semaphore",
        "juc-15-latch-barrier",
      ],
    },
    {
      text: "并发容器",
      icon: "boxes-stacked",
      prefix: "collections/",
      collapsible: true,
      children: [
        "juc-16-concurrent-collections",
        "juc-17-blocking-queue",
        "juc-18-queue-selection",
      ],
    },
    {
      text: "线程池",
      icon: "gears",
      prefix: "pool/",
      collapsible: true,
      children: [
        "juc-19-thread-pool",
        "juc-20-reject-pitfalls",
        "juc-21-dynamic-params",
        "juc-22-forkjoin",
      ],
    },
    {
      text: "性能扩展",
      icon: "gauge-high",
      prefix: "performance/",
      collapsible: true,
      children: [
        "juc-23-disruptor",
        "juc-24-summary",
      ],
    },
  ],
  "/软件架构/": [
    "",
    {
      text: "入门与动机",
      icon: "book",
      prefix: "ddd-basics/",
      collapsible: true,
      children: [
        "ddd-01-what-is-ddd",
        "ddd-02-scrum-anemic",
        "ddd-03-solid-oo",
      ],
    },
    {
      text: "战略设计",
      icon: "sitemap",
      prefix: "ddd-strategy/",
      collapsible: true,
      children: [
        "ddd-04-concepts-bc",
        "ddd-05-microservice-split",
        "ddd-06-strategic-modeling",
        "ddd-07-ubiquitous-eventstorm",
      ],
    },
    {
      text: "战术与分层",
      icon: "layer-group",
      prefix: "ddd-tactics/",
      collapsible: true,
      children: [
        "ddd-08-layered-models",
        "ddd-09-domain-primitive",
        "ddd-10-hexagonal-new-app",
        "ddd-11-repository",
        "ddd-12-domain-layer",
        "ddd-13-application-interface",
      ],
    },
    {
      text: "落地实践",
      icon: "gears",
      prefix: "ddd-practice/",
      collapsible: true,
      children: [
        "ddd-14-cola-scaffold",
        "ddd-15-acl-summary",
      ],
    },
  ],
  "/性能调优/": [
    "",
    {
      text: "JVM",
      icon: "gears",
      prefix: "jvm/",
      collapsible: true,
      children: [
        "jvm-01-overview",
        "jvm-02-classloader",
        "jvm-03-memory-model",
        "jvm-04-object-allocation",
        "jvm-05-classfile-bytecode",
        "jvm-06-execution-engine",
        "jvm-07-parnew-cms",
        "jvm-08-g1-zgc",
        "jvm-09-tuning-tools",
        "jvm-10-constant-pool",
        "jvm-11-jdk17-features",
        "jvm-12-jdk17-gc",
      ],
    },
    {
      text: "Tomcat",
      icon: "server",
      prefix: "tomcat/",
      collapsible: true,
      children: [
        "tomcat-01-architecture",
        "tomcat-02-thread-tuning",
        "tomcat-03-classloader-hotdeploy",
        "tomcat-04-summary",
      ],
    },
  ],
  "/数据库/": [
    "",
    {
      text: "MySQL",
      icon: "database",
      prefix: "mysql/",
      collapsible: true,
      children: [
        "mysql-01-architecture",
        "mysql-02-index-structure",
        "mysql-03-explain",
        "mysql-04-index-opt-1",
        "mysql-05-index-opt-2",
        "mysql-06-transaction-lock",
        "mysql-07-mvcc-bufferpool",
        "mysql-08-innodb-logs",
        "mysql-09-mysql8-features",
        "mysql-10-replication-ha",
      ],
    },
  ],
  "/分布式/": [
    "",
    {
      text: "Seata",
      icon: "network-wired",
      prefix: "seata/",
      collapsible: true,
      children: [
        "seata-01-distributed-tx-overview",
        "seata-02-at-mode",
        "seata-03-tc-server",
        "seata-04-at-tm-rm",
        "seata-05-tcc-practice",
        "seata-06-tcc-issues",
        "seata-07-tcc-source",
        "seata-08-isolation-interview",
      ],
    },
  ],
  "/微服务/": [
    "",
    {
      text: "Spring Boot",
      icon: "leaf",
      prefix: "springboot/",
      collapsible: true,
      children: [
        "boot-01-handwritten-core",
        "boot-02-startup-source",
        "boot-03-autoconfigure",
      ],
    },
    {
      text: "Spring Cloud Alibaba",
      icon: "cloud",
      prefix: "springcloud/",
      collapsible: true,
      children: [
        "sca-01-microservice-overview",
        "sca-02-practice-summary",
      ],
    },
    {
      text: "Nacos",
      icon: "sitemap",
      prefix: "nacos/",
      collapsible: true,
      children: [
        "nacos-01-architecture",
        "nacos-02-grpc",
        "nacos-03-config-center",
      ],
    },
    {
      text: "Sentinel",
      icon: "shield-halved",
      prefix: "sentinel/",
      collapsible: true,
      children: [
        "sentinel-01-architecture",
      ],
    },
    {
      text: "Seata 内核",
      icon: "database",
      prefix: "seata/",
      collapsible: true,
      children: [
        "seata-kernel-01-source",
      ],
    },
    {
      text: "Spring 扩展",
      icon: "puzzle-piece",
      prefix: "spring-ext/",
      collapsible: true,
      children: [
        "spring-ext-01-extension-points",
      ],
    },
    {
      text: "路线与占位",
      icon: "map",
      prefix: "roadmap/",
      collapsible: true,
      children: [
        "ms-12-roadmap-placeholders",
      ],
    },
  ],
  "/源码剖析/": [
    "",
    {
      text: "Spring 6 源码",
      icon: "leaf",
      prefix: "spring6/",
      collapsible: true,
      children: [
        "s6-01-compile",
        "s6-02-overview",
        "s6-03-components",
        "s6-04-handwritten",
        "s6-05-ioc-load",
        "s6-06-config-class",
        "s6-07-circular-dep",
        "s6-08-async-bean",
        "s6-09-bean-postprocessor",
        "s6-10-aop",
        "s6-11-transaction",
        "s6-12-event",
        "s6-13-extension-points",
        "s6-14-mybatis",
        "s6-15-aot",
        "s6-16-mvc-flow",
        "s6-17-mvc-parent-child",
      ],
    },
    {
      text: "MyBatis",
      icon: "database",
      prefix: "mybatis/",
      collapsible: true,
      children: [
        "mb-01-intro-basic",
        "mb-02-config",
        "mb-03-xml-params-result",
        "mb-04-xml-result-map",
        "mb-05-xml-dynamic-sql",
        "mb-06-xml-cache",
        "mb-07-generator-pagehelper",
        "mb-08-ssm",
        "mb-09-mybatis-plus",
        "mb-18-config-parse",
        "mb-19-sql-exec-flow",
      ],
    },
  ],
  "/tag/": false,
  "/category/": false,
  "/article/": false,
  "/star/": false,
  "/timeline/": false,
});
