  "/云原生/": [
    "",
    {
      text: "云原生基础",
      icon: "seedling",
      prefix: "foundation/",
      collapsible: true,
      children: [
        "foundation-01-云原生",
        "foundation-02-虚拟化技术",
        "foundation-03-云计算",
      ],
    },
    {
      text: "Docker",
      icon: "cube",
      prefix: "docker/",
      collapsible: true,
      children: [
        "docker-01-what-is-docker",
        "docker-03-engine-platform",
        "docker-02-container-vs-vm",
        "docker-04-install",
        "docker-05-container-and-image",
        "docker-06-container-commands",
        "docker-07-enter-container",
        "docker-08-image-transfer",
        "docker-10-harbor",
        "docker-09-dockerfile",
        "docker-19-process-view",
        "docker-21-daemon-runtime",
        "docker-16-tech-foundation",
        "docker-17-unionfs",
        "docker-18-namespace",
        "docker-20-cgroups",
        "docker-11-network",
        "docker-13-compose",
      ],
    },
    {
      text: "Docker 进阶",
      icon: "cubes",
      prefix: "docker-extra/",
      collapsible: true,
      children: [
        "docker-extra-01-如何通过docker部署https访问的nginx应用",
        "docker-extra-02-container-runtime-docker",
      ],
    },
    {
      text: "Containerd",
      icon: "box",
      prefix: "containerd/",
      collapsible: true,
      children: [
        "containerd-01-轻量级容器管理工具-containerd",
      ],
    },
    {
      text: "Kubernetes",
      icon: "dharmachakra",
      prefix: "k8s/",
      collapsible: true,
      children: [
        "k8s-01-cloud-native",
        "k8s-02-macro-architecture",
        "k8s-03-minikube-runtime",
        "k8s-04-objects-kubectl",
        "k8s-05-pod-workload",
        "k8s-06-deployment-rs",
        "k8s-07-daemon-stateful-job",
        "k8s-08-hpa-cri-crd",
        "k8s-09-service-l4",
        "k8s-10-network-dns",
        "k8s-11-pv-pvc",
        "k8s-12-ingress-l7",
        "k8s-13-release-strategies",
        "k8s-14-service-mesh-istio",
        "k8s-15-harbor-springcloud",
        "k8s-16-secret-configmap",
        "k8s-17-jenkins-canary",
        "k8s-18-prometheus-hpa",
        "k8s-19-custom-metrics",
        "k8s-20-jvm-in-container",
      ],
    },
    {
      text: "K8s 课程笔记",
      icon: "book",
      prefix: "k8s-course/",
      collapsible: true,
      children: [
        "k8s-course-01-kubernetes配置与密钥管理-configmap-secret",
        "k8s-course-02-kubernetes集群使用容器镜像仓库harbor",
        "k8s-course-03-kubernetes集群公共服务",
        "k8s-course-04-kubernetes集群java项目上云部署",
        "k8s-course-05-kubernetes集群python项目上云部署",
        "k8s-course-06-kubernetes集群golang项目上云部署",
        "k8s-course-07-kubernetes日志收集方案-elk",
        "k8s-course-08-kubernetes日志收集方案-efk",
        "k8s-course-09-rocketmq部署",
        "k8s-course-10-kubernetes集群包管理解决方案及应用商店-helm-kubeapps",
        "k8s-course-11-安全容器运行时-kata",
        "k8s-course-12-新型沙箱安全容器运行时-gvisor",
        "k8s-course-13-如何使用kubernetes实现服务自动伸缩-hpa-vpa",
        "k8s-course-14-如何基于事件驱动扩展k8s应用的深度实践",
        "k8s-course-15-如何通过prometheus及hpa实现kubernetes应用自动水平伸缩",
        "k8s-course-16-如何使用argo-rollouts实现金丝雀发布",
        "k8s-course-17-原地升级及全链路灰度发布解决方案-openkruise",
        "k8s-course-18-kubeadm极速部署kubernetes-1-24版本集群",
        "k8s-course-19-kubeadm部署高可用kubernetes集群-1-21-0",
        "k8s-course-20-使用rke构建企业生产kubernetes集群",
        "k8s-course-21-kubernetes高可用集群二进制部署-runtime-docker",
        "k8s-course-22-kubernetes集群ui及主机资源监控",
        "k8s-course-23-使用sealos部署kubernetes集群并实现集群管理",
        "k8s-course-24-debian-12部署k8s-1-28版集群",
        "k8s-course-25-kubeadm极速部署kubernetes-1-27-1版本集群",
        "k8s-course-26-基于cri-o实现k8s-1-28二进制高可用集群",
        "k8s-course-27-基于docker实现k8s-1-28二进制高可用集群",
        "k8s-course-28-kubespray部署k8s-1-26集群",
        "k8s-course-29-kubernetes集群部署口袋工具-minikube",
        "k8s-course-30-kubernetes介绍与集群架构",
        "k8s-course-31-kubernetes集群部署方式说明",
        "k8s-course-32-kubeadm部署单master节点kubernetes集群-1-21-0",
        "k8s-course-33-kubeadm极速部署kubernetes-1-28版本集群",
        "k8s-course-34-如何基于ubuntu-24-04部署原生k8s-1-30-0集群",
        "k8s-course-35-如何基于ubuntu-24-04部署原生k8s-1-31-0集群",
        "k8s-course-36-如何基于ubuntu-24-04部署原生k8s-1-32-0集群",
        "k8s-course-37-k8s集群网络插件cilium-网络加速器-部署及使用验证",
        "k8s-course-38-国产化openeuler-欧拉-操作系统部署k8s集群",
        "k8s-course-39-国产化麒麟操作系统部署k8s",
        "k8s-course-40-基于cri-o容器运行时部署k8s集群",
        "k8s-course-41-基于docker部署k8s-1-28集群",
        "k8s-course-42-基于openeuler操作系统使用isula容器运行时部署k8s集群",
        "k8s-course-43-ubuntu-22-04部署k8s集群",
        "k8s-course-44-ubuntu-23-04部署k8s集群",
        "k8s-course-45-如何基于ubuntu-22-04部署原生k8s-1-29-0集群",
        "k8s-course-46-如何通过kube-vip实现k8s集群高可用",
        "k8s-course-47-kubeadm快速部署kubernetes-1-29-0版本集群",
        "k8s-course-48-如何基于ubuntu-24-04部署原生k8s-1-30-0集群",
        "k8s-course-49-如何通过k0s部署k8s二进制集群",
        "k8s-course-50-rke2方式部署k8s集群-高可用",
        "k8s-course-51-kubernetes集群客户端命令-kubectl",
        "k8s-course-52-kubernetes集群node管理",
        "k8s-course-53-kubernetes集群声明式文件yaml",
        "k8s-course-54-kubernetes集群命名空间-namespace",
        "k8s-course-55-kubernetes集群核心概念",
        "k8s-course-56-kubernetes核心概念-pod",
        "k8s-course-57-kubernetes核心概念-controller",
        "k8s-course-58-kubernetes核心概念-controller控制器之statefulset",
        "k8s-course-59-kubernetes核心概念-service",
        "k8s-course-60-kubernetes集群-服务暴露-nginx-ingress-controller",
        "k8s-course-61-ingress-nginx-controller-1-4-0-最新版本部署方法",
        "k8s-course-62-基于ingress-nginx实现灰度发布系统",
        "k8s-course-63-kubernetes集群服务暴露-traefik",
        "k8s-course-64-kubernetes高可用集群二进制部署-runtime-containerd",
        "k8s-course-65-k8s-1-26集群部署-容器运行时为containerd",
        "k8s-course-66-基于containerd实现k8s-1-28二进制高可用集群",
        "k8s-course-67-如何基于ubuntu-24-04部署原生k8s-1-32-0集群",
        "k8s-course-68-基于containerd容器运行时部署k8s-1-28集群",
      ],
    },
    {
      text: "K8s 网络",
      icon: "network-wired",
      prefix: "network/",
      collapsible: true,
      children: [
        "network-01-k8s-1-26-underlay网络方案-hybridnet",
        "network-02-k8s-1-22-版本双栈协议-ipv4-ipv6-集群部署",
      ],
    },
    {
      text: "K8s 存储",
      icon: "hard-drive",
      prefix: "storage/",
      collapsible: true,
      children: [
        "storage-01-kubernetes持久化存储卷及存储动态供给",
        "storage-02-k8s集群存储解决方案-glusterfs",
        "storage-03-如何基于kubernetes使用分布式块存储longhorn",
      ],
    },
    {
      text: "DevOps / GitOps",
      icon: "gears",
      prefix: "devops/",
      collapsible: true,
      children: [
        "devops-01-what-is-devops",
        "devops-02-gitops",
        "devops-03-ci-basics",
        "devops-04-jenkins-pipeline",
        "devops-05-github-actions",
        "devops-06-sonarqube",
        "devops-07-harbor-ci",
        "devops-08-env-planning",
        "devops-09-argocd-install",
        "devops-10-argocd-ops",
        "devops-11-app-manifests",
        "devops-12-gitlab-ci-argocd",
        "devops-13-github-actions-argocd",
        "devops-14-jenkins-argocd",
        "devops-15-multicluster-rollback",
      ],
    },
    {
      text: "Serverless",
      icon: "cloud",
      prefix: "serverless/",
      collapsible: true,
      children: [
        "serverless-01-使用knative平台环境说明",
        "serverless-02-现阶段云原生应用领域介绍",
        "serverless-03-为什么要引入serverless",
        "serverless-04-serverless应用场景",
        "serverless-05-sererless架构优缺点",
        "serverless-06-knative介绍",
        "serverless-07-knative在云原生应用领域的定位",
        "serverless-08-knative与云原生平台的三个最佳实践",
        "serverless-09-knative-serving",
        "serverless-10-knative-eventing",
        "serverless-11-kn工具安装及应用",
        "serverless-12-knative-eventing组件及应用案例",
        "serverless-13-tekton安装",
        "serverless-14-tekton初体验",
        "serverless-15-构建自定义tag镜像应用案例",
        "serverless-16-tekton流水线中使用workspace应用案例",
        "serverless-17-使用-tekton-sidecar-实现-docker-in-docker-构建",
        "serverless-18-gitlab-触发-tekton-任务构建",
        "serverless-19-使用-tekton-实现自动化流水线",
        "serverless-20-tekton-与-argo-cd-结合实现-gitops",
        "serverless-21-knative-可观测性-使用prometheus与grafana监控",
        "serverless-22-efk",
        "serverless-23-openfaas-函数即服务",
      ],
    },
    {
      text: "可观测性",
      icon: "eye",
      prefix: "observability/",
      collapsible: true,
      children: [
        "observability-01-如何通过opentelemetry实现云原生应用全链路状态跟踪",
        "observability-02-prometheus安装",
        "observability-03-grafana对接prometheus数据源",
        "observability-04-prometheus告警alertmanager组件",
        "observability-05-prometheus告警媒介-企业微信",
        "observability-06-prometheus告警媒介-钉钉",
        "observability-07-容器化构建prometheus监控系统",
        "observability-08-容器监控方案-cadvisor",
        "observability-09-k8s监控方案-ksm-kube-state-metrics",
        "observability-10-helm部署prometheus及应用",
        "observability-11-helm部署prometheus及应用",
        "observability-12-如何通过pixie实现kubernetes云原生应用可观测",
      ],
    },
    {
      text: "Prometheus",
      icon: "chart-line",
      prefix: "prometheus/",
      collapsible: true,
      children: [
        "prometheus-01-1-1为什么学透prometheus可以进大厂",
        "prometheus-02-1-2运维和运维开发同学在prometheus上的学习重点",
        "prometheus-03-1-3-为什么本节课的老师最专业",
        "prometheus-04-10-1-使用ansible部署-redis-exporter",
        "prometheus-05-10-2-grafana上导入模板看图并讲解告警",
        "prometheus-06-10-3-查看源码-讲解采集原理",
        "prometheus-07-11-1-监控kafka和zookeeper的jvm",
        "prometheus-08-11-2-导入grafana大盘和指标讲解",
        "prometheus-09-12-1-应用场景和部署",
        "prometheus-100-33-4-为什么remote-read查询series比直接查询要慢很多和源码解读",
        "prometheus-10-12-2-使用prometheus-sdk向pushgateway打点",
        "prometheus-101-33-5-remote实战项目之设计prometheus数据源的结构",
        "prometheus-102-33-6-read的代码-查询series方法和queryengine的rangequery方法",
        "prometheus-103-33-7-write的代码编写和测试",
        "prometheus-104-34-1-uber开源的m3db简介",
        "prometheus-105-34-2-m3db上手搭建",
        "prometheus-106-34-3-m3db-oom的内存火焰图和内存分配器加油模型源码解读",
        "prometheus-107-34-4-m3db调优踩坑问题总结",
        "prometheus-108-35-1-thanos项目介绍和二进制部署",
        "prometheus-109-35-2-thanos-sidecar源码阅读",
        "prometheus-110-35-3-thanos-store-源码阅读",
        "prometheus-11-13-1-alertmanager核心功能点介绍和安装部署",
        "prometheus-111-35-4-thanos-query-源码阅读",
        "prometheus-112-35-5-thanos-compactor-源码阅读",
        "prometheus-113-35-6-thanos-rule-源码阅读",
        "prometheus-114-36-1-kube-prometheus项目讲解和安装部署",
        "prometheus-115-36-2-内置的k8s采集任务分析",
        "prometheus-116-36-3-grafana-dashboard看图分析",
        "prometheus-117-36-4-prometheus告警和预聚合分析",
        "prometheus-118-36-5-自定义指标接入prometheus-operator",
        "prometheus-119-37-1-prometheus管理接口源码讲解",
        "prometheus-120-37-2-prometheus分析接口源码讲解",
        "prometheus-12-13-2-编写go程序充当告警触发端和接收端",
        "prometheus-121-37-3-prometheus5大数据查询接口",
        "prometheus-122-38-1-range-query和querylog源码解读",
        "prometheus-123-39-1-用最近1天的内存平均使用率等出业务资源利用率报表",
        "prometheus-124-4-1-prometheus基本概念-sample数据点",
        "prometheus-125-4-2-prometheus四种查询类型",
        "prometheus-126-4-3-四种标签匹配模式",
        "prometheus-127-4-4-四种数据类型",
        "prometheus-128-4-5-时间范围选择器",
        "prometheus-129-4-6-实用promql介绍",
        "prometheus-130-40-1-高基数查询原因总结和判定高基数的依据",
        "prometheus-13-13-3-alertmanager分组功能",
        "prometheus-131-40-2-预聚合和prometheus-record使用",
        "prometheus-132-40-3-prometheus预聚合源码解读",
        "prometheus-133-41-1-预聚合提速实战项目之需求分析和架构设计",
        "prometheus-134-41-2-ansible拷贝日志文件-解析日志并判断重查询",
        "prometheus-135-41-3-将重查询记录增量更新到consul和redis中",
        "prometheus-136-41-4-修改confd源码增加静态分片功能",
        "prometheus-137-41-5-nginx拦截prometheus查询请求使用lua脚本做promql的检查替换",
        "prometheus-138-41-6-安装部署-效果测试-架构回顾",
        "prometheus-139-42-1-从一条告警的触发分析prometheus-alert告警源码",
        "prometheus-140-42-2-告警触发trigger模块单点问题和高可用解决方案",
        "prometheus-14-13-4告警抑制实例",
        "prometheus-141-43-1-配置alertmanager高可用并测试",
        "prometheus-142-43-2-gossip协议解读",
        "prometheus-143-43-3-alertmanager流水线处理源码解读",
        "prometheus-144-44-1-告警自愈之回调重启服务实战",
        "prometheus-145-5-1编写ansibleplaybook批量安装二进制",
        "prometheus-146-5-2黑白名单配置",
        "prometheus-147-5-3-sdk指标和配置本地采集目录",
        "prometheus-148-5-4-配置prometheus采集通过http请求参数过滤采集器",
        "prometheus-149-5-5-node-exporter采集原理简介",
        "prometheus-150-5-6-node-exporter二开新增自定义模块",
        "prometheus-15-13-5-告警静默",
        "prometheus-151-6-1-grafana和mysql安装",
        "prometheus-152-6-2-基础功能介绍",
        "prometheus-153-6-3-panel中操作",
        "prometheus-154-6-4-设置表格tables",
        "prometheus-155-6-5-使用变量查询",
        "prometheus-156-6-6-使用dashboard商城搜索导入模板",
        "prometheus-157-7-1-使用ansible部署-blackbox-exporter",
        "prometheus-158-7-2-页面访问http探测-模块和探针介绍",
        "prometheus-159-7-3-多实例采集的说明relabel配置",
        "prometheus-160-7-4-ssh探测和ping探测使用",
        "prometheus-16-13-6-编写go代码接收webhook的告警发送钉钉",
        "prometheus-161-7-5-grafana上导入模板看图并讲解告警",
        "prometheus-162-7-6-blackbox框架源码和http探测源码解读",
        "prometheus-163-7-7-prometheus-relabel-address替换源码解析",
        "prometheus-164-8-1-使用ansible部署mysql-exporter-注入dsn环境变量",
        "prometheus-165-8-2-grafana上导入模板看图并讲解告警",
        "prometheus-166-8-3-修改mysqld-exporter源码-改造成类似blackbox的探针型-实现一对多探测",
        "prometheus-167-9-1-使用ansible部署process-exporter",
        "prometheus-168-9-2-grafana-上导入模板看图并讲解告警",
        "prometheus-169-9-3-查看源码-讲解采集原理",
        "prometheus-170-msb-prometheus大纲",
        "prometheus-17-14-1-为什么说k8s中监控更复杂了",
        "prometheus-18-14-2-k8s中我们都需要监控哪些组件",
        "prometheus-19-15-1-使用kubeadm-10分钟部署k8集群",
        "prometheus-20-15-10-在k8s部署grafana-deployment并导入k8s大盘",
        "prometheus-21-15-2-定义一个prometheus数据存储使用的pv",
        "prometheus-22-15-3-storageclass和volumeclaimtemplates",
        "prometheus-23-15-4-prometheus使用的clusterrole等rbac对象",
        "prometheus-24-15-5-创建监控控制平面的service",
        "prometheus-25-15-6-创建prometheus使用的配置configmap",
        "prometheus-26-15-7-创建prometheus的statsfulset配置",
        "prometheus-27-15-8-在k8s部署prometheus-statefulset",
        "prometheus-28-15-9-grafana-deployment-yaml讲解",
        "prometheus-29-16-1-k8s容器基础资源指标采集原理讲解",
        "prometheus-30-16-2-k8s容器基础资源指标讲解",
        "prometheus-31-16-3-k8s容器cpu内存告警指标与资源request和limit",
        "prometheus-32-17-1ksm关注指标讲解-pod和node状态的统计",
        "prometheus-33-17-2-ksm源码讲解",
        "prometheus-34-18-1-k8s服务组件之4大黄金指标讲解",
        "prometheus-35-18-2-k8s-apiserver监控源码解读",
        "prometheus-36-19-1-使用k8s的sdk编写一个项目获取pod和node信息",
        "prometheus-37-19-2-编写dockerfile和k8s-yaml",
        "prometheus-38-19-3-打镜像部署到k8s中-prometheus配置采集并在grafana看图",
        "prometheus-39-2-1达到大厂要求的学习目标",
        "prometheus-40-20-1-分析pull模型在k8s中的应用-对比push模型",
        "prometheus-41-21-1-k8s接口鉴权token认证和prometheus的实现",
        "prometheus-42-21-2-k8s中etcd的tls双向认证原理解析",
        "prometheus-43-22-1-k8s不同role级别的服务发现",
        "prometheus-44-22-2-k8s中ksm采集的使用的dns解析",
        "prometheus-45-22-3-解读k8s服务发现源码",
        "prometheus-46-23-1-k8s监控中标签relabel的应用和原理",
        "prometheus-47-23-2-prometheus为k8s做的4大适配工作",
        "prometheus-48-24-1-prometheus-exporter管理",
        "prometheus-49-24-2-prometheus-target管理",
        "prometheus-50-24-3-基于文件的服务发现模式",
        "prometheus-51-24-4-基于consul服务发现模式",
        "prometheus-52-24-5-基于http服务发现模式",
        "prometheus-53-24-6-监控系统在采集侧对接运维平台",
        "prometheus-54-25-1-降低采集资源消耗的收益和无用监控指标的判定依据",
        "prometheus-55-25-2-采集端高基数的现象和原因",
        "prometheus-56-25-3-使用relabel中的drop将对应的无用指标丢弃",
        "prometheus-57-26-1-分位值summary和histogram对比",
        "prometheus-58-26-2-histogram线性插值法源码解读",
        "prometheus-59-26-3-summary源码解读",
        "prometheus-60-27-1-采集端单点问题原因和危害-静态分片方案的弊端",
        "prometheus-61-27-2-动态分片方案和它要解决的问题",
        "prometheus-62-27-3-一致性哈希算法介绍",
        "prometheus-63-27-4-一致性哈希算法的golang实现和迁移率测试",
        "prometheus-64-27-5-go实战项目prome-shard的代码准备工作",
        "prometheus-65-27-6-consul注册服务-抽象获取target的方法",
        "prometheus-66-27-7-开启一致性哈希环变更监听处理和consul-watch服务",
        "prometheus-67-27-8-把target做一致性哈希进行分发",
        "prometheus-68-27-9-调用go-ansible执行playbook拷贝json文件重载采集器",
        "prometheus-69-28-1-pushgateway单点问题和动态分片方案介绍",
        "prometheus-70-28-2-go实战项目dynamic-sharding的代码准备工作",
        "prometheus-71-28-3-一致性哈希和推送数据的redirect流程",
        "prometheus-72-28-4-编译运行测试效果",
        "prometheus-73-29-1-时序监控和日志监控的对比-分析日志监控的核心诉求",
        "prometheus-74-29-2-golang实战项目log2metrics架构说明",
        "prometheus-75-29-3-准备工作-编写配置文件-解析配置-校验正则-设置log",
        "prometheus-76-29-4-日志任务增量更新管理器和具体的日志job对象",
        "prometheus-77-29-5-日志消费组和日志正则处理对象analyspoint",
        "prometheus-78-29-6-时序统计的结构体对象和metrics结果打点方法",
        "prometheus-79-29-7-编译运行-读取日志配置看图",
        "prometheus-80-3-1-prometheus二进制安装",
        "prometheus-81-3-2ui功能讲解之graph页面",
        "prometheus-82-3-3prometheus命令行参数讲解",
        "prometheus-83-3-4-prometheus配置文件和6大模块讲解",
        "prometheus-84-3-5-static-configs采集配置源码解读",
        "prometheus-85-3-6-prometheus命令行参数讲解",
        "prometheus-86-3-7-热更新源码解读",
        "prometheus-87-30-1-时序数据库tsdb的典型特点",
        "prometheus-88-30-2-不得不谈的lsm-分层结构和lsm数据结构",
        "prometheus-89-31-1-时序数据压缩的必要和facebook-gorilla压缩算法简介",
        "prometheus-90-31-2-dod压缩和相关的prometheus源码解读",
        "prometheus-91-31-3-xor压缩和相关的prometheus源码解读",
        "prometheus-92-32-1-prometheus倒排索引源码解析",
        "prometheus-93-32-2-prometheus倒排索引统计功能",
        "prometheus-94-32-3-mmap的在io提速上的应用和prometheus的应用",
        "prometheus-95-32-4-prometheus存储磁盘数据结构和存储参数",
        "prometheus-96-32-5-compact目的和源码解读",
        "prometheus-97-33-1-prometheus本地存储单点问题和remote解决方案",
        "prometheus-98-33-2-prometheus联邦功能源码解读和它的问题",
        "prometheus-99-33-3-prometheus-低成本存储multi-remote-read方案说明",
      ],
    },
    {
      text: "PaaS 平台",
      icon: "layer-group",
      prefix: "paas/",
      collapsible: true,
      children: [
        "paas-01-在linux上以all-in-one模式安装kubernetes-kubesphere",
        "paas-02-在kubernetes集群上最小化安装kubesphere",
        "paas-03-kubesphere-3-4-0-抢鲜版",
        "paas-04-kubesphere中集成apisix",
        "paas-05-kubesphere集成本地容器镜像仓库-harbor",
        "paas-06-kubesphere部署三高商城组织架构说明",
        "paas-07-微服务项目-基于kubernetes集群paas云平台-kubesphere部署",
        "paas-08-kubesphere多租户系统应用",
        "paas-09-kubesphere集成本地容器镜像仓库-harbor",
        "paas-10-kubesphere中集成apisix",
      ],
    },
    {
      text: "微服务实战",
      icon: "sitemap",
      prefix: "microservices/",
      collapsible: true,
      children: [
        "microservices-01-kubernetes集群公共服务-dns",
        "microservices-02-kubernetes集群公共服务-harbor",
        "microservices-03-openeelb部署及应用",
        "microservices-04-微服务部署前中间件部署",
        "microservices-05-kubernetes集群中部署服务思路",
        "microservices-06-k8s集群中部署服务之应用环境配置",
        "microservices-07-k8s集群中部署服务之dockerfile文件准备",
        "microservices-08-k8s集群中部署服务之部署描述文件准备",
        "microservices-09-k8s集群中部署项目之流水线",
        "microservices-10-k8s集群中部署项目之数据库准备",
        "microservices-11-k8s集群中流水线部署微服务",
        "microservices-12-k8s集群中部署微服务项目前端代理服务-nginx",
        "microservices-13-k8s集群中部署微服务vue",
        "microservices-14-kubeadm极速部署kubernetes-1-24版本集群",
        "microservices-15-kubernetes集群公共服务-dns",
        "microservices-16-coredns级联本地dns服务器",
        "microservices-17-kubernetes集群公共服务-harbor",
        "microservices-18-openeelb部署及应用",
        "microservices-19-微服务部署前中间件部署",
        "microservices-20-严选项目代码获取",
        "microservices-21-严选商城项目部署前配置说明",
        "microservices-22-严选商城项目部署前配置及数据库导入说明",
        "microservices-23-严选项目流水线基础环境准备",
        "microservices-24-严选商城项目部署前流水线编写",
      ],
    },
    {
      text: "多集群",
      icon: "diagram-project",
      prefix: "multicluster/",
      collapsible: true,
      children: [
        "multicluster-01-如何使用terraform实现对kubernetes集群中资源对象进行管理",
        "multicluster-02-如何通过cilium-cluster-mesh实现kubernetes多集群方案",
        "multicluster-03-kubernetes集群舰队管理-kurator",
        "multicluster-04-karmada部署及应用",
      ],
    },
    {
      text: "备份恢复",
      icon: "box-archive",
      prefix: "backup/",
      collapsible: true,
      children: [
        "backup-01-kubernetes集群备份与恢复管理利器velero",
      ],
    },
    {
      text: "公有云",
      icon: "cloud-arrow-up",
      prefix: "public-cloud/",
      collapsible: true,
      children: [
        "public-cloud-01-阿里云容器服务-ack",
      ],
    },
    {
      text: "边缘计算",
      icon: "wifi",
      prefix: "edge/",
      collapsible: true,
      children: [
        "edge-01-k8s-1-22-版本集群部署",
        "edge-02-云原生边缘计算-kubeedge-部署",
      ],
    },
    {
      text: "大数据与 ML",
      icon: "database",
      prefix: "bigdata/",
      collapsible: true,
      children: [
        "bigdata-01-笔记-大数据hdfs分布式文件系统搭建",
        "bigdata-02-笔记-flink基于kubernetes部署",
        "bigdata-03-笔记-spark与kubernetes整合",
        "bigdata-04-基于k8s构建机器学习平台kubeflow",
      ],
    },
    {
      text: "数据服务",
      icon: "server",
      prefix: "data-service/",
      collapsible: true,
      children: [
        "data-service-01-基于k8s构建云原生基础设施平台-kubeblocks",
      ],
    },
    {
      text: "KubeVirt",
      icon: "desktop",
      prefix: "kubevirt/",
      collapsible: true,
      children: [
        "kubevirt-01-kubernetes管理虚拟机利器kubevirt",
      ],
    },
    {
      text: "Operator 开发",
      icon: "code",
      prefix: "operator/",
      collapsible: true,
      children: [
        "operator-01-windows主机中构建适用于k8s-operator开发环境",
        "operator-02-windows主机中构建适用于k8s-operator开发环境",
      ],
    },
    {
      text: "Golang",
      icon: "golang",
      prefix: "golang/",
      collapsible: true,
      children: [
        "golang-01-overview",
        "golang-02-part01",
        "golang-03-part02",
        "golang-04-part03",
        "golang-05-part04",
        "golang-06-part05",
        "golang-07-part06",
        "golang-08-part07",
        "golang-09-part08",
        "golang-10-part09",
        "golang-11-part10",
        "golang-12-part11",
        "golang-13-part12",
        "golang-14-part13",
        "golang-15-part14",
        "golang-16-part15",
        "golang-17-part16",
        "golang-18-unit10",
        "golang-19-unit11",
        "golang-20-unit12",
        "golang-21-unit13",
        "golang-22-unit14",
        "golang-23-unit2",
        "golang-24-unit3",
        "golang-25-unit4",
        "golang-26-unit5",
        "golang-27-unit6",
        "golang-28-unit7",
        "golang-29-unit8",
        "golang-30-unit9",
      ],
    },
    {
      text: "VIP 专题",
      icon: "star",
      prefix: "vip/",
      collapsible: true,
      children: [
        "vip-01-almalinux-9操作系统",
        "vip-02-kubeadm极速部署kubernetes-1-29版本集群",
        "vip-03-基于ingress-nginx实现灰度发布系统",
      ],
    },
    {
      text: "面试",
      icon: "user-tie",
      prefix: "interview/",
      collapsible: true,
      children: [
        "interview-01-kubernetes-2024-03-更新-kubernetes面试题",
      ],
    },
  ],
